### ISSUE TITLE
Highlighting position is broken

### ISSUE THREAD

**Issue by cpkio** [folke/trouble.nvim#105]
After `:TroubleToggle lsp_workspace_diagnostics` while scrolling through list the highlights are misplaced:
![2021-10-22_235558](https://user-images.githubusercontent.com/1917113/138522153-40702020-a4e6-4543-b9eb-ce4b9b640aed.png)
In the list in shows correct positions (199, 69), they are underlined by linter in the picture. The gray background is the wrong positioning. It seems you're using byte offset, when you should glyph offset (since Cyrillics is 2-byte in UTF-8).

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
