### ISSUE TITLE
Errors from entire project not just opened buffers

### ISSUE THREAD

**Issue by kaykhancheckpoint** [folke/trouble.nvim#107]
Hi i really like this plugin.

I have a typescript project and i want to be able to see the errors that occur in all of the files in my project not just the buffers that i have open. Is this possible?

For example if i rename a function, trouble will show me error for the buffer that i have open which contains the old fnction name, but for the files that i dont have open that also contain the old function name, it does not show me an error.

**Comment by folke** [comment]
That's a limitation of the typescript lsp server. We can only show what we get from LSP. Nothing more

**Comment by simonlearnscoding** [comment]
is there a way to make the lsp scan all files in the src folder though?
