### ISSUE TITLE
Multi-line diagnostics

### ISSUE THREAD

**Issue by ii14** [folke/trouble.nvim#11]
Hey, would you consider supporting multi-line diagnostics? Right now all lines are concatenated and displayed in a single line, while `vim.lsp.diagnostic.show_line_diagnostics()` displays them correctly.

![screenshot-210427-094654](https://user-images.githubusercontent.com/59243201/116205091-afd8d980-a73d-11eb-9781-63e9df9a2490.png)

**Comment by folke** [comment]
I'll see what I can do. At the minimum, I can add a keyboard shortcut to open a small floating window with the multi-line text.

**Comment by elkowar** [comment]
Such a keyboard shortcut would be fantastic! although just having a way to expand the error in the list would also be very welcome ^^

**Comment by folke** [comment]
Just added this. It's the configurable `hover` action and defaults to `K`

**Comment by elkowar** [comment]
Another cool idea I just had here would be to allow for having a split pane in the bottom list, where the right pane just shows the multiline error of the currently hovered error, and the error list is on the left. Although this hover solution works really well, too! Thanks a ton already!

**Comment by folke** [comment]
@elkowar I'll just keep the hover for now, but thank you for the suggestion :)

**Comment by Soupstraw** [comment]
I'd prefer if all errors in the trouble window are shown multiline. This could be an option in the configuration.
If the option is turned on, the errors would look something like this:

```
v file1.txt  4
     error  • Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
              magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
              consequat. 
     error  • Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore 
              magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo 
              consequat. 
```

**Comment by Kaanta0** [comment]
hello everyone, was this added as an option ? or do we only have the `hover` key ?
