### ISSUE TITLE
Use tagstack

### ISSUE THREAD

**Issue by Saecki** [folke/trouble.nvim#110]
I like to use `<c-i>` and `<c-o>` to navigate back from where I jumped. Sadly `trouble.nvim` doesn't seem to add an entry to the tagstack when jumping to a location. The nvim-lsp-client does [this](https://github.com/neovim/neovim/blob/b8eabb37b1d4e267a4db7e639e8cbdec2ed64b8e/runtime/lua/vim/lsp/util.lua#L1029) to enable that functionality.

I might get around implementing this on my own, just wanted to leave this here in the meantime.

**Comment by meijieru** [comment]
Same here.
Currently `<c-i>` and `<c-o>` behaviors make the goto useless.
@Saecki Have you solved this problem?

**Comment by Saecki** [comment]
@meijieru Not yet.

**Comment by qsdrqs** [comment]
I add this code in my config as the temporary solution:
```lua
local util = require("trouble.util")
local util_jump_to_item = util.jump_to_item
util.jump_to_item = function(win, precmd, item)
  -- add mark to jump back
  vim.cmd("normal! m'")
  util_jump_to_item(win, precmd, item)
end
```

**Comment by Saecki** [comment]
I think this was fixed by https://github.com/folke/trouble.nvim/commit/f0477b0e78d9a16ff326e356235876ff3f87882d.
