### ISSUE TITLE
Wrap text in Trouble Diagnostics?

### ISSUE THREAD

**Issue by LandonSchropp** [folke/trouble.nvim#114]
Apologies if this is a dumb question, but I couldn't find a good answer while searching.

Is it possible to wrap the text in the trouble diagnostics?

Here's an example where wrapping the text would make things much easier to read without having to scroll.

<img width="1055" alt="Screen Shot 2021-11-14 at 5 39 04 PM" src="https://user-images.githubusercontent.com/361591/141703323-00c5babc-3f11-48b5-8852-f287dd742a36.png">

Thanks!

**Comment by pbogut** [comment]
It's just vim buffer so you can do `:set wrap`. It doesn't look pretty though.

**Comment by LandonSchropp** [comment]
It seems like Trouble [disabled this option](https://github.com/folke/trouble.nvim/blob/756f09de113a775ab16ba6d26c090616b40a999d/lua/trouble/view.lua#L142) by default. Is there a way to override this? Thanks!

**Comment by folke** [comment]
You can press "K" (shift-k) to see a popup with the full text

**Comment by Balrrach** [comment]
I think this can be archived using autocmd. Since the file name is `Trouble` I tried the following but didn't work:
```vim
au BufRead,BufNewFile Trouble setlocal wrap linebreak	" Line wrap in Trouble files
```
If anyone has an idea on how to make it work, please, let me know!

**Comment by carlesandres** [comment]
I would love to have as an option that Trouble buffers always wrap text

**Comment by roobert** [comment]
I've opened a PR to add this feature [here](https://github.com/folke/trouble.nvim/pull/326)

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
