### ISSUE TITLE
Feature: Allow files to be highlighted based on highest severity

### ISSUE THREAD

**Issue by mtrajano** [folke/trouble.nvim#120]
This would allow the user to see a high level overview of which files have errors, warnings, etc.. similar to how vscode highlights the tab with the worst severity. This is useful if you have a lot of files open and you have them folded by default. Let me know if this sounds interesting and I can get a pr out for it. 

I got it working by making some small changes to `providers.group` to have file attributes, instead of just returning an array of diagnostics for each file. This allows for some other interesting possibilities: sort by files with the worst severity, seprate the count by severity etc.. Example of how it can look:

<img width="767" alt="Screen Shot 2021-11-21 at 11 45 48 AM" src="https://user-images.githubusercontent.com/4333381/142771603-cf28391c-a306-4a7e-af24-90720ba459c9.png">

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
