### ISSUE TITLE
Use with nvim-lint?

### ISSUE THREAD

**Issue by sbromberger** [folke/trouble.nvim#123]
Hi,

I love this plugin - thanks for writing and supporting it.

I was hoping to get some help integrating Trouble with nvim-lint - right now, the linter issues don't toggle Trouble (I have auto-open on). I have a companion issue at https://github.com/mfussenegger/nvim-lint/issues/123 but I'm not sure how to proceed with a proposed fix. Any hints would be greatly appreciated.

**Comment by folke** [comment]
I just pushed a bunch of changes related to the new vim.diagnostic API. Can you check if this works now?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
