### ISSUE TITLE
Invalid window/buffer id crash opening a buffer with fzf.vim when errors are shown (TroubleToggle on)

### ISSUE THREAD

**Issue by David-Else** [folke/trouble.nvim#125]
I am using Neovim 0.6, but I think this also happened on 0.5.1 (sorry, I can't be certain!)

1. Open nvim, use `fzf.vim` history to open a markdown file
2. Open the error window with `leader xx`
3. Open another file using `fzf.vim` history
```
Error executing vim.schedule lua callback: ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:364: Invalid window id: 1002                                                     
stack traceback:
        [C]: in function 'get_cursor'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:364: in function 'get_line'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:371: in function 'current_item'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:444: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
Press ENTER or type command to continue
Error executing vim.schedule lua callback: ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:102: Invalid buffer id: 3
stack traceback:
        [C]: in function 'set_option'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:102: in function 'unlock'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:88: in function 'render'
        ...onfig/nvim/plugged/trouble.nvim/lua/trouble/renderer.lua:74: in function 'cb'
        ...nvim/plugged/trouble.nvim/lua/trouble/providers/init.lua:46: in function 'cb'
        .../nvim/plugged/trouble.nvim/lua/trouble/providers/lsp.lua:17: in function 'provider'
        ...nvim/plugged/trouble.nvim/lua/trouble/providers/init.lua:38: in function 'get'
        ...onfig/nvim/plugged/trouble.nvim/lua/trouble/renderer.lua:37: in function 'render'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:124: in function 'update'
        ...d/.config/nvim/plugged/trouble.nvim/lua/trouble/view.lua:286: in function 'fn'
        vim.lua:415: in function 'cb'
        vim.lua:285: in function <vim.lua:285>
```
Once this error has happened you can toggle between the buffers using `fzf.vim` with no more crashes.

EDIT: I just got this crash without using `fzf.vim`, so I don't think it is anything to do with that:

![Screenshot from 2021-12-01 13-13-58](https://user-images.githubusercontent.com/12832280/144241001-e8cfa8bc-226a-4772-9442-e4da827db629.png)

**Comment by MattSPalmer** [comment]
I'm also encountering the `invalid window id` error with a different path to reproduction. I have `fzf.vim` installed but it's not really a part of the steps to reproduce.

To reproduce:
- call `:Trouble workspace_diagnostics`
- run the lua snippet `require('trouble').next({ skip_groups = true, jump = true })` (or `.previous()`)

Strangely the second step isn't enough on its own, you have to do it after invoking the diagnostics.

```
E5108: Error executing lua ...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:365: Invalid window id: 1001
stack traceback:
        [C]: in function 'get_cursor'
        `...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:365:` in function 'get_line'
        ...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:393: in function 'previous_item'
        ...site/pack/packer/start/trouble.nvim/lua/trouble/init.lua:241: in function 'previous'
        [string ":lua"]:1: in main chunk
```

**Comment by t2m4k1** [comment]
For me disabling the auto_preview fixed this issue. It's just a workaround but maybe that helps you.
`require("trouble").setup{auto_preview = false}`

**Comment by ekokotov** [comment]
The same issue on the first start trouble commands =(

**Comment by cosmikwolf** [comment]
also hitting this same issue. 
setting auto_preview to false resolves the problem for me.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
