### ISSUE TITLE
Feature: toggle Warnings on/off with mapped key

### ISSUE THREAD

**Issue by marcomayer** [folke/trouble.nvim#128]
Often I'd like to ignore all the (linter) warnings and just focus/see real errors. For this I'd wish there'd be a key I can press to toggle Warnings on/off when Trouble is open. (If I find some time I'll do it myself and send a PR.)

**Comment by icholy** [comment]
I want this functionality to hide eslint warnings.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
