### ISSUE TITLE
DiagnosticChanged err on startup

### ISSUE THREAD

**Issue by hemedani** [folke/trouble.nvim#132]
I have this err on every start-up nvim :
```shell
E216: No such group or event: DiagnosticChanged * lua require'trouble'.refresh({auto = true, provider = "diagnostics"})
```

**Comment by folke** [comment]
Whar version of Nevoim are you using?

**Comment by Irubataru** [comment]
I have the same problem, I am on `NVIM v0.6.0-dev+623-gdd8a4e2c2`

**Comment by folke** [comment]
You should either use 0.5, 0.6 or main. You seem to be using a pre-release 0.6 instead.

**Comment by Irubataru** [comment]
Ah okay, I suppose as `nvim` 0.6 has finally released that I can downgrade from the AUR `neovim-git` package to the regular packman `neovim` package.

**Comment by folke** [comment]
@Irubataru it should also work in the nightlies after the 0.6 release. Plus in 0.5. Just not in nightlies after 0.5 and before 0.6 :)

**Comment by nagy135** [comment]
Also faced this today, but updating AUR neovim-git solved it ...still, looks like "has nvim 0.6" approach doesnt seem to be sufficient since not all 0.6 versions are compatible with this change.

**Comment by hemedani** [comment]
sorry my nvim version is :
```
NVIM v0.6.0-dev+2039-g16d4af6d2
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by folke** [comment]
As I mentioned before, trouble works for:
- stable 0.5
- stable 0.6
- any nightly **after** 0.6

The change for `DiagnosticChanged` was done in Neovim right before the 0.6 release. I'm not planning to do any weird hacks to make it work for versions before that.

Closing this.

**Comment by Thesmader** [comment]
I build Neovim from source and I am facing this error on latest HEAD. Will the error persist for source builds?

```sh
nvim --version

NVIM v0.6.0-dev+555-gf26b39131
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by thesmader@manjaro

Features: +acl +iconv +tui
See ":help feature-compile"
```

**Comment by folke** [comment]
@Thesmader that is not the latest head. Latest head is 0.7.0 something...
