### ISSUE TITLE
Null-ls document diagnostics not shown

### ISSUE THREAD

**Issue by tbung** [folke/trouble.nvim#133]
When using null-ls document diagnostics don't show up. As far as I can tell this is not an issue with trouble it self but with the API trouble uses: `vim.lsp.diagnostic.get` does not return them. My suggestion is to switch to the new diagnostics api `vim.diagnostic.get`, which does work with null-ls.

I currently don't have the time or knowledge to say where the origin of the issue lies here or whether it should be fixed somewhere else than trouble, but I fixed this for myself by replacing the api call and would be happy to provide a pull request.

Thanks!

**Comment by dlvhdr** [comment]
I don't see diagnostics from `lspconfig` too...
I configured ESLint by calling `require('lspconfig').diagnosticls.setup`

**Comment by ahal** [comment]
I'm seeing this as well, would you mind posting a PR or diff @tbung ? Even if it's not the right solution it can help others work around the issue in the meantime.

**Comment by folke** [comment]
I just made a bunch of changes to fix all of this.
