### ISSUE TITLE
[deprecated] use of depracated lsp api in `trouble/providers/diagnostic.lua`

### ISSUE THREAD

**Issue by kunzaatko** [folke/trouble.nvim#137]
`vim.lsp.diagnostic.get` is deprecated in favour of `vim.diagnostic.get`.

**Comment by kunzaatko** [comment]
You can assign it to me, but I will have time only in about 2 weeks.

**Comment by kunzaatko** [comment]
akinsho/bufferline.nvim#272

**Comment by folke** [comment]
Those deprecated methods are only used when vim.diagnostic is not available, so the warnings you're getting are not coming from Trouble. They;re probably from bufferline.

**Comment by kunzaatko** [comment]
Oh, sorry. I looked over the code more and it makes sense. Thank you!
