### ISSUE TITLE
[Feature]: put cursor to next/previous file in trouble list

### ISSUE THREAD

**Issue by younger-1** [folke/trouble.nvim#139]
In `workspace_diagnostics` mode, there may have multiple file in troubls's list. It will be nice to use `J` and `K` to put cursor to next file and previous file, which I found useful when looking through all my diagnostics.

**Comment by younger-1** [comment]
The behavior is like [nvim-bqf's](https://github.com/kevinhwang91/nvim-bqf#function-table) `prevfile` and `nextfile`.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by simonmandlik** [comment]
@folke is this really fixed in `v3`? (move)[https://github.com/folke/trouble.nvim/blob/971ad925ff6fdb57950d7c5d4c5d65e2cdbaecec/lua/trouble/view/init.lua#L314] only accepts arguments irrelevant to skipping to next/prev file
