### ISSUE TITLE
auto_jump does not work when the Trouble window is open

### ISSUE THREAD

**Issue by dessaya** [folke/trouble.nvim#144]
`Trouble lsp_definitions` with `auto_jump` works fine, unless the Trouble window is already open. In that case, the Trouble window is focused instead.

**Comment by JulesNP** [comment]
I've been having the same issue. As a workaround, I've setup the functions for my mappings as follows:

```lua
function()
    vim.cmd [[normal m']]
    trouble.close()
    trouble.open "lsp_definitions"
end
```

The `m'` is also used to workaround issue #143 by manually setting a jumplist position.
