### ISSUE TITLE
How to apply LSP quickfix?

### ISSUE THREAD

**Issue by Logarithmus** [folke/trouble.nvim#148]
On pressing Enter in the list of quickfixes my cursor just jumps to the line of code. How to apply quickfix after that?

**Comment by OnionHat** [comment]
Do you mean code action? If so the command you are looking for, if your lsp is configured correctly, is `lua vim.lsp.buf.code_action()`.

**Comment by Logarithmus** [comment]
Yes, that's exactly what I was looking for. I've solved it a long time ago, just forgot about this issue.
