### ISSUE TITLE
Cursor position outside buffer when opening Trouble

### ISSUE THREAD

**Issue by anhari** [folke/trouble.nvim#151]
### Description

Run into this issue when opening with `:Trouble` or navigating to the trouble window after it's been opened:

``` 
|| Error executing vim.schedule lua callback: ...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:453: Cursor position outside buffer
|| stack traceback:
|| 	[C]: in function 'nvim_win_set_cursor'
|| 	...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:453: in function ''
|| 	vim.lua: in function <vim.lua:0>
```

### Environment details

Trouble config:

``` lua
  require("trouble").setup {
    auto_open = true,
    auto_close = true
  }
```

Neovim version info:

```
NVIM v0.7.0-dev+836-g55a59e56e
Build type: Release
LuaJIT 2.1.0-beta3
```

**Comment by gmr458** [comment]
same error
![image](https://user-images.githubusercontent.com/53343401/153981917-54e39558-e5e7-42e2-a19f-ad38cce7e77c.png)

**Comment by rickalex21** [comment]
I'm getting the same error.

**Comment by cassava** [comment]
I'm also having this error.

**Comment by tkolleh** [comment]
Any luck finding a root cause of this issue? Getting this when I open trouble on a Scala file with nvim-metals attached.

**Comment by krims0n32** [comment]
Also having this issue.

**Comment by gmr458** [comment]
I experienced this error in February 2022, I remember that a day later it disappeared. The only advice I can give is to look at the README, maybe you have to update some configuration, update the plugin, I don't know if the version of Neovim you are using has something to do with it.

**Comment by jjo93sa** [comment]
I'm seeing this too:
```
Error executing vim.schedule lua callback: ...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:469: Cursor position outside buffer
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        ...site/pack/packer/start/trouble.nvim/lua/trouble/view.lua:469: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Running the latest Neovim from HomeBrew: neovim--0.8.3.arm64_ventura.bottle.tar.gz. I've also checked I'm running the latest versions of all the plugins... Does anyone have an idea what this might be?

**Comment by rudenkornk** [comment]
Same issue, trouble version "67337644e38144b444d026b0df2dc5fa0038930f", neovim version:
```bash
NVIM v0.8.3
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az183-550

Features: +acl +iconv +tui
```

**Comment by JuanferM** [comment]
I was able to reproduce this on neovim (NVIM v0.9.1). Before calling line 488 (view.lua), I just checked if the corresponding index is not out of bounds.

Line 488 :
```
vim.api.nvim_win_set_cursor(self.parent, { item.start.line + 1, item.start.character })
```

was changed to :
```
if vim.api.nvim_buf_line_count(item.bufnr) > item.start.line + 1 then
    vim.api.nvim_win_set_cursor(self.parent, { item.start.line + 1, item.start.character })
end
```

Trouble seems to work fine after the changes and the issue is solved.
