### ISSUE TITLE
[Bug]: Toggling the Trouble Pane/Window destroys vertical layout with vsplit windows/panes

### ISSUE THREAD

**Issue by joehannes** [folke/trouble.nvim#155]
## Problem

When I got vertically split windows it seems `TroubleClose` would simple add the space its own window had taken vertically (height) to the bottom most window/pane of split windows/panes.
Vice Verse also `Trouble` seems to to take the space its own window needs from the upper windows in a vertical split layout only and no matter what the layout was.

Together, toggling Trouble on/off, which I do for example automatically before and after every session auto-save (write-file),
destroys a vertical split-window/pane-layout. adding a lot of vertical size to the bottom most pane/window only.

## Solution/Feature Request/Bugfix:

don't just take/remove the space Trouble needs from the bottom-most pane/window, resize the vertical layout adding/removing the Trouble-Windows height relatively/in-relation of the current vertical layout (in %).

Actually this is a real problem for me with my current setup, but I quite like `Trouble` ... hmm, I would even consider giving up nvims vertical splits altogether rather then giving up trouble, but as is now vertical splits become quite useless, always being autoresized to uncomfortable dimensions :-)

Please fix, would be awesome!!! <3

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
