### ISSUE TITLE
Expected lua number

### ISSUE THREAD

**Issue by Mte90** [folke/trouble.nvim#161]
![immagine](https://user-images.githubusercontent.com/403283/152157886-627f19f3-de96-4633-8102-3ff17b018da2.png)

I got that with `Troubletoggle lsp_references`

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
