### ISSUE TITLE
Document available lua functions in the README.md

### ISSUE THREAD

**Issue by samuelludwig** [folke/trouble.nvim#165]
Currently the keybind examples make use of available `<cmd>` style calls. Seeing as we now have access to `vim.keymap.set`, I think it would be useful to also detail the names of the functions made available by `require('trouble')` and what args they may take. (For instance: `require('trouble').toggle()` and `require('trouble').toggle('workspace_diagnositcs')`)

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
