### ISSUE TITLE
consider to add a license?

### ISSUE THREAD

**Issue by haolian9** [folke/trouble.nvim#168]
with my previous issue, i actually forked this repo and made some changes, and then i found touble.nvim did not have a license which means i [can not do that](https://choosealicense.com/no-permission/).

will you consider adding a license for this awesome repo?

**Comment by vladdoster** [comment]
@haolian9 This was fixed in commit [691d490cc4eadc430d226fa7d77aaa84e2e0a125](https://github.com/folke/trouble.nvim/commit/691d490cc4eadc430d226fa7d77aaa84e2e0a125).

**Comment by haolian9** [comment]
that's great!
many thanks to the author and this awesome project!
