### ISSUE TITLE
Initial invocation locking up neovim?

### ISSUE THREAD

**Issue by ristillu** [folke/trouble.nvim#169]
Hey folke a colleague just noticed trouble and I've started using it with a goal of replacing ALE (I'm using LSP but was still using ALE in my qf window until today).

My question (without browsing your code) is, is the initial invocation synchronous or something? I'm opening a single python file in a repo with over 3000 python files. I'm using pylsp and pyright. Pyright kicks in pretty heavily whether trouble is on or off, but when I turn `:Trouble` on, my session locks up for about 30 seconds while trouble sorts itself out. I get lags of a few seconds per keypress and stuttering until after about 30 seconds things seem normal again. This file has 323 errors in it, so there's a bit going on. I'm just curious if it's possible to make those initial comms between trouble and LSP asynchronous (if they are not already).

I'm also a big fan of which-key, love your work.

**Comment by iabdelkareem** [comment]
+1 I'm experiencing the same problem

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
