### ISSUE TITLE
Is it possilble to filter out diagnostics depending on their level?

### ISSUE THREAD

**Issue by kristupas-gaidys** [folke/trouble.nvim#170]
In a a big project the deprecated tags throw errors, it would be really convenient to filter them out

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
