### ISSUE TITLE
How to enable inline errors.

### ISSUE THREAD

**Issue by Lalit64** [folke/trouble.nvim#171]
Hey @folke. I've been using trouble.nvim and couldn't find a way to enable inline errors.

**Comment by yryrgogo** [comment]
@Lalit64 
Hi, if you want to display lsp diagnostics, it is the lsp option, not trouble.

````
vim.lsp.handlers["textDocument/publishDiagnostics"] =
	vim.lsp.with(vim.lsp.diagnostic.on_publish_diagnostics, { virtual_text = true })
```

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
