### ISSUE TITLE
How to move cursor back to diagnostic window? (Question)

### ISSUE THREAD

**Issue by winkee01** [folke/trouble.nvim#172]
Sorry, I am new to this plugin, it looks so appealing but I have a small question.

So I type `:Trouble [mode]` to enter the diagnostic window, moving the cursor up and down to review the error/warning info, after I press Enter key, the cursor jumps to the source code window. 

My question is: after I fix the error, how can I take the cursor back to the diagnostic window?

Thanks in advance

**Comment by AstroShen** [comment]
<c-w>p is what you are looking for

**Comment by winkee01** [comment]
p is paste in source code window

**Comment by haolian9** [comment]
try `<c-w>j` or `:Trouble`

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
