### ISSUE TITLE
default TroubleText link to Normal plays bad with cursorline when background is not none

### ISSUE THREAD

**Issue by rebelot** [folke/trouble.nvim#174]
Hi! first, thanks for the amazing plugin!

As per title, I've noticed that the default highlight of `TroubleText` links to `Normal`, however, when `Normal` defines a `guibg` the cursorline will not override the text background, resulting in an unpleasent feel.

test:
`:hi TroubleText guifg=fg guibg=bg` (BAD) vs `:hi TroubleText guifg=fg guibg=none` (GOOD)

**Comment by scienceplease** [comment]
@rebelot
I'm having the same issue. Were you able to identify what line(s) in the source this is happening on? I couldn't pinpoint it myself.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
