### ISSUE TITLE
Fix: Invalid Severity Mapping in Quickfix/Loclist Providers 

### ISSUE THREAD

**Issue by scienceplease** [folke/trouble.nvim#181]
Neovim's diagnostic severity `HINT` should map to Vim/quickfix `note`, which is represented by `N` [\[1\]](https://github.com/neovim/neovim/blob/a48a0a4f7b2b1255025ceb128f6cc97fa0f992aa/runtime/lua/vim/diagnostic.lua#L1541) [\[2\]](https://github.com/neovim/neovim/blob/a48a0a4f7b2b1255025ceb128f6cc97fa0f992aa/runtime/lua/vim/diagnostic.lua#L18). Trouble currently maps `HINT` to nonexistent `H`. This results in diagnostic hints in quickfix/loclist being displayed as "other" in Trouble. To produce this bug, add diagnostics to your loclist or quickfix lists using `vim.diagnostic.setloclist()` or `vim.diagnostic.setqflist()` and view either with `:Trouble loclist` or `:Trouble quickfix` respectively. I confirmed the fix below resolves this issue.

**Current**:
https://github.com/folke/trouble.nvim/blob/691d490cc4eadc430d226fa7d77aaa84e2e0a125/lua/trouble/providers/qf.lua#L5

**Fix**:
```lua
local severities = { E = 1, W = 2, I = 3, N = 4 }
```

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
