### ISSUE TITLE
Telescope configuration in the README does not work

### ISSUE THREAD

**Issue by raj-magesh** [folke/trouble.nvim#182]
As far as I can tell, the Telescope configuration suggested in the README of this repo doesn't work.

```
local actions = require("telescope.actions")
local trouble = require("trouble.providers.telescope")

require('telescope').setup {
    defaults = {
        -- Default configuration for telescope goes here:
        mappings = {
          i = { ["<c-e>"] = trouble.open_with_trouble },
          n = { ["<c-e>"] = trouble.open_with_trouble },
        }
        -- remaining config
    }
}
```

It also differs markedly from other Telescope extensions which require something like `require('telescope').load_extension("dap")`, for instance.

**Comment by diegodox** [comment]
Is this work for you?
```lua
["<C-e>"] = function(prompt_bufnr, _mode)
    require("trouble.providers.telescope").open_with_trouble(prompt_bufnr, _mode)
end,
```

**Comment by baggiponte** [comment]
On a side note, I don't really understand what the configs do. I don't think it's supposed to open the diagnostics in Telescope, but any Telescope panel inside Trouble's?

**Comment by folke** [comment]
@baggiponte you can open search results from Telescope in Trouble.

Like live-grep in Telescope, hit `<c-t>` and you have all the resulsts in trouble

**Comment by avegancafe** [comment]
I'm also running into this issue, I would try to debug but when I try to open telescope results with trouble it appears to just hang, until I hit ctrl-c

**Comment by pythops** [comment]
Anyone figured it out ?

**Comment by avegancafe** [comment]
Unfortunately no @pythops , still happening :/ such a bummer 'cause I love trouble and telescope. A smidge difficult to debug without knowing both well though

**Comment by ADkun** [comment]
**I have encountered this issue too.**

**Comment by chikko80** [comment]
Same for me, can't setup trouble with telescope, maybe an extension approach would be much easier

**Comment by jla2000** [comment]
Anyone got it working? Seems like it still hangs when trying to send the telescope results to trouble...

**Comment by wambldor** [comment]
This solution works for me, I use nvchad , so lazy.nvim.
the part with ui-select you can of course leave out.

`{
    "nvim-telescope/telescope.nvim",
    dependencies = {
      "nvim-lua/plenary.nvim",
      "nvim-telescope/telescope-ui-select.nvim",
      "folke/trouble.nvim",
    },
    setup = {
      extensions = {
        ["ui-select"] = {
          require("telescope.themes").get_dropdown {},
        },
      },
    },
    config = function(_, opts)
      local actions = require("telescope.actions")
      local trouble = require("trouble.providers.telescope")
      opts.defaults.mappings  = {
            i = { ["<c-o>"] = trouble.open_with_trouble },
            n = { ["<c-o>"] = trouble.open_with_trouble },
      }
      require("telescope").setup(opts)
      require("telescope").load_extension "ui-select"
    end,
  }`

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
