### ISSUE TITLE
Programmatically switch position (bottom/right)?

### ISSUE THREAD

**Issue by divan** [folke/trouble.nvim#186]
Hey! Thanks for the **amazing** plugin.

Sometimes it's useful to have Trouble window on the right, but sometimes I need to see long lines. I would love to be able to switch that on the fly – like toggle Trouble window position from bottom to right and vice-versa.

Is it possible to make this programmatically?

Thanks in advance!

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
