### ISSUE TITLE
There seems to be something wrong with the quickfix window

### ISSUE THREAD

**Issue by j2501987804** [folke/trouble.nvim#188]
neovim0.7
os:arch-wsl macos
The cursor moves by itself, and two windows are opened.

![QQ录屏2022060115295520226117832](https://user-images.githubusercontent.com/41771911/171369393-559c563f-f9ba-48f9-99ad-3fcb14a4ab8e.gif)

**Comment by pspiagicw** [comment]
I too encountered this problem

**Comment by Fabian-programmer** [comment]
Same problem nvim 0.8.1

**Comment by AlwaysIngame** [comment]
Have this problem as well. Tried some older commits which also have this same problem.

**Comment by denolehov** [comment]
Same issue here :/

**Comment by FledgeXu** [comment]
Same issue here.

**Comment by MariaSolOs** [comment]
I just encountered this issue too. To reproduce it:
1. Download the files found [here](https://github.com/weiliy/dnvim-code/tree/3683a215af5173be197c7f0ce2ba9a65e2c17778/quickfix/wakeup).
2. Open Neovim in that directory, and run `:make` (assuming you have `gcc` installed).
3. Open Trouble's quickfix list and go the last item.

Notice what happens:

https://github.com/folke/trouble.nvim/assets/62502207/4a3d064e-aad2-4d0d-a508-2032d1a5edd6

The error you see at the end is:
<img width="1022" alt="image" src="https://github.com/folke/trouble.nvim/assets/62502207/3915cb90-e41e-407c-bd1b-ab0a5ba1558c">

**Comment by YodaEmbedding** [comment]
See also:

- https://github.com/folke/trouble.nvim/issues/87
- https://github.com/folke/trouble.nvim/issues/336

**Comment by YodaEmbedding** [comment]
The common thing in all the screen captures is when it says `[1, 1]`.

![336](https://user-images.githubusercontent.com/2996796/272694419-2f6e8c52-6e8e-43ea-be52-a30a7a93c4c1.mp4)

![87](https://user-images.githubusercontent.com/6608056/131682214-d8ca195f-631c-42ac-bef2-1466098043d3.png)

---

My guess is that this happens whenever there's no exact line number or position associated with a given error, and then Trouble fills in a default value of `[1, 1]`.

![trouble](https://github.com/folke/trouble.nvim/assets/721196/286d5945-2f53-4f2c-aedc-af793c0e96db)

The troublesome line is marked as "BAD". When the cursor is hovered over it, everything goes haywire and the cursor starts moving right all on its own.
