### ISSUE TITLE
Workspace diagnostics shows only open buffers for ts files with tsserver and null-ls

### ISSUE THREAD

**Issue by rphuber** [folke/trouble.nvim#192]
Using both tsserver and null-ls with prettier and eslint I only get diagnostic reports from open buffers instead of the entire project.  I read in another issue that it seems to be an issue with tsserver but was wondering if this was an issue with the null-ls plugin as well?  Any feedback would be helpful.  Thanks!

**Comment by joelxr** [comment]
Same thing happens to me after fresh installing it.

**Comment by Alex-vZyl** [comment]
Duplicate of #107?

**Comment by folke** [comment]
This has nothing to do with Trouble. Most language servers only show issue from opened files

**Comment by pencilcheck** [comment]
Well, if that's the case, it shouldn't be called workspace, it should be called lsp-wide instead. this is misleading.

**Comment by folke** [comment]
@pencilcheck it is called workspace diagnostics in the lsp spec, so that's how it will be called in trouble. ok?
