### ISSUE TITLE
Feature: Display item number in list

### ISSUE THREAD

**Issue by dlants** [folke/trouble.nvim#194]
I think it's useful to quickly see how many items are in the list. For example, if you're trying to narrow down a regexp (watching the number of matches decrease) or fiddling with a test (hopefully making fewer tests fail).

With a quickfix list, since the lines are numbered, you can go to the bottom of the list (with `G`) and see the total number of items relatively quickly. Also, while working your way through the list, it's easy to see your progress (have I done 10 of the items or 30?).

It would be nice to have a similar feature in trouble.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
