### ISSUE TITLE
Is it possible to hide virtual text from Trouble?

### ISSUE THREAD

**Issue by miversen33** [folke/trouble.nvim#195]
As virtual text is a bit constrained, I would like the ability to pick/choose which plugins actually display in my virtualetext area of neovim. I am not seeing a way to limit this in Trouble, is that something that can be done?

An example, I would like my colorsigns column to continue working, and the quickfix to still be populated with trouble info (as it currently does). I just dont want trouble displaying stuff in my virtualtext area (or at least, I would like the ability to configure this).

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by willhansen** [comment]
How do we change it in the dev branch?

**Comment by miversen33** [comment]
@willhansen  that depends completely on what package manager you are using. You will need to consult with your package manage documentation on how to chose the branch of your plugin. If you are _not_ using a package manager, simply run the `git checkout dev` command from the project directory in your plugin folder.

Making the assumption that you use a package manager (as you likely are), you will need to go research there.

**Comment by willhansen** [comment]
**in** the dev branch, not **to** the dev branch

Near as I can tell, it's something along these lines:
`vim.diagnostic.Opts = {virtual_text = false}`

**Comment by miversen33** [comment]
Reading is hard, that is a good question actually! I honestly stopped using trouble forever ago so this hasn't been a thorn in my side anymore. Hopefully folke can shed some light on it :)
