### ISSUE TITLE
readme typo

### ISSUE THREAD

**Issue by mahor1221** [folke/trouble.nvim#196]
There is a typo on line 164 of README.md

163: * lsp_definitions: definitions of the word ...
164: * lsp_type_definitions:  ~~tupe~~ **type** definitions of ...
165: * quickfix: [quickfix](https://neovim.io/doc/user/quickfix.html) items

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
