### ISSUE TITLE
attempt to index local 'finish'

### ISSUE THREAD

**Issue by obmutescences** [folke/trouble.nvim#197]
when do cmd :Trouble

![Snipaste_2022-07-26_11-19-42](https://user-images.githubusercontent.com/29330637/180916004-e77643cc-c4e9-4891-a911-67bb382f121e.png)

**Comment by JuniorSuperTux** [comment]
Same here

**Comment by ramtej** [comment]
Same. Any ideas on this?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
