### ISSUE TITLE
Display all trouble in one buffer

### ISSUE THREAD

**Issue by gilice** [folke/trouble.nvim#198]
Hi, 
this might be a very beginner-ish question. I am using Trouble together with https://github.com/folke/todo-comments.nvim and it would be amazing if it could display both types of errors (todo comments and LSP diagnostics) in the same buffer.
Has anyone done this yet? can you give me an example?

**Comment by pkazmier** [comment]
I just discovered both of these packages and have the exact same question. It would be nice if the TODOs were included in Trouble's diagnostics. One stop shopping 😄

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
