### ISSUE TITLE
Keep Trouble window quickfix list up to date as the document is edited

### ISSUE THREAD

**Issue by Hubro** [folke/trouble.nvim#201]
Currently, using `:Trouble quickfix` with gives a worse developer experience than using the built-in quickfix window plus `:cnext`/`:cprevious`.

The quickfix `:cnext`/`:cprevious` commands will jump to the correct line even if you've added/deleted lines higher up in the document. However, Trouble with `require("trouble").next/previous(...)` will jump to the exact line number from the quickfix list.

Any time I fix a linter warning, jumping to the next linter warning will take me to an unrelated line, which is a massive pain. After a few fixes, the jump location may not even be anywhere near the location of the linter warning, making the Trouble quickfix list useless.

Should the locations in the Trouble quickfix window be kept up-to-date as lines are added/deleted from the document? This would make it much, much easier to work with. Are there any drawbacks to doing this?

---

The logic sounds pretty trivial, and it would have to run any time a line is added or deleted:

- Any time a line is added, any quickfix list item with a *higher* line number than the added line should have its row number incremented by one
- Any time a line is deleted, any quickfix list item with a *higher* line number than the deleted line should have its row number decremented by one

I'm not very familiar with writing plugins for Vim/NVim, but I assume there are autocommands that trigger on document edits and APIs for figuring out which lines were added/removed.

**Comment by Hubro** [comment]
Or, come to think of it, perhaps pressing `<Enter>` on a line in Trouble could just execute the same action that would be executed in the built-in quickfix list? That way, whatever logic Vim is doing to keep the line number up to date would be reused.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by xzbdmw** [comment]
@folke This feature seems not implemented in v3

**Comment by folke** [comment]
Allright, seems I didn't ready this fully.

I'll see if this can be added.

**Comment by xzbdmw** [comment]
Ah, it is indeed refreshed when I call   `require("trouble").next({ skip_groups = true, jump = true })`, but `getqflist` will return linenumber that higher than actual line count if I delete some lines, cause trouble to throw errors

**Comment by folke** [comment]
It actually already works. You can do `r` in the trouble buffer to refresh.
Almost finished adding the correct refresh events to trouble.

**Comment by folke** [comment]
Fixed

**Comment by folke** [comment]
It only updates on `TextChanged`. If you also want it to update during insert, then you can add `TextChangedI` to your config.

**Comment by xzbdmw** [comment]
@folke If you delete lines between qflist results, trouble will throw errors, a simple gif showing that

https://github.com/folke/trouble.nvim/assets/97848247/2d277d83-c344-4ac0-bc7c-07d9b4625a7f

**Comment by folke** [comment]
@xzbdmw should be fixed now. I also fixed the event. It should only listen on changes on the main buffer, but it was listening on all buffer changes, inlcuding those of the trouble windows.
