### ISSUE TITLE
jump_close reverts back to original location

### ISSUE THREAD

**Issue by bytesizedpcs** [folke/trouble.nvim#202]
When using the `jump_close` keybind with `lsp_references` you are sent back to your original location, not the one that was selected within the list.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
