### ISSUE TITLE
cannot get it to work with coc.nvim and rust-analyzer

### ISSUE THREAD

**Issue by arctic-penguin** [folke/trouble.nvim#203]
First of all, I tried to follow this: https://github.com/folke/trouble.nvim/issues/12 and also tried with the fork. Neither worked for me.

My setup:
* neovim v0.7.2
* coc.nvim up-to-date
* coc-rust-analyzer plugin
* `:checkhealth` is happy

`coc-settings.json`
```json
{
    "codeLens.enable": true,
    "python.formatting.provider": "blackd",
    "rust-analyzer.server.path": "/usr/bin/rust-analyzer",
    "rust-analyzer.inlayHints.reborrowHints.enable": "always",
    "rust-analyzer.checkOnSave.command": "clippy",
    "coc.preferences.extensionUpdateCheck": "daily",
    "coc.preferences.formatOnSaveFiletypes": ["rust"],
    "coc.preferences.formatOnType": true,
    "coc.preferences.formatOnTypeFiletypes": ["rust"],
    "json.format.enable": true
}
```

Here is a screenshot where I introduced an error.  CoC and rust-analyzer correctly show the location of the errors, the quick-fixes, etc. The lower bar is trouble, which I opened with `\xx`, and it always shows empty.

![screen](https://user-images.githubusercontent.com/103587359/185598670-e0a35ff7-c18b-4a00-a993-7d472ffa590f.png)

Am I missing something here?

**Comment by ciehanski** [comment]
My setup is similar and I am also running into this issue. Below I've listed a temporary nvim mapping workaround that will at least manually check ```coc``` and fill Trouble's loclist when the ```gL``` command is run:

```vim
nmap <silent> gL <cmd>call coc#rpc#request('fillDiagnostics', [bufnr('%')])<CR><cmd>Trouble loclist<CR>
```

It's pretty manual and not the best experience, but it works.
