### ISSUE TITLE
Can't split a window while closing another

### ISSUE THREAD

**Issue by mrusme** [folke/trouble.nvim#204]
Hey there, sometimes I'm getting the following error when closing multiple tabs and trying to quit neovim:

```
Error executing lua ...cal/share/nvim/plugged/trouble.nvim/lua/trouble/view.lua:348: Vim(new):E242: Can't split a window while closing another
```

A whole list of this error is being shown at the end before nvim quits.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
