### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by fastbodin** [folke/trouble.nvim#207]
Please excuse that this question is rather simple but I wanted to ask if there is a way to navigate back and forth between the Trouble buffer when it is open and your document in question? I understand that :TroubleToggle opens the Trouble buffer and that you can move around via hjkl in the buffer and hit Enter/Return to move from the selected item in the Trouble buffer to that item in the main document, but how do you go back and forth?

Thanks in advance.

**Comment by yavorski** [comment]
<kbd>ESC</kbd> or <kbd>CTRL</kbd>+<kbd>w</kbd>+<kbd>w</kbd>
