### ISSUE TITLE
Pressing q takes you to first split rather than last active split

### ISSUE THREAD

**Issue by Pranshugoyal** [folke/trouble.nvim#209]
Pressing q exits the trouble window and takes you back, but if you have multiple windows open then correct behaviour should be to take the user back to the window where they came from. If it's still available.

I also attempted fixing it on my end, its a small change and seems like it works, I've not yet tried all scenarios. But if you're interested I can send a pull request.

**Comment by haolian9** [comment]
yeah, i had reported a similar issue before #189

**Comment by Pranshugoyal** [comment]
This is the solution I implemented.

**Comment by Pranshugoyal** [comment]
Yes @okuuva

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
