### ISSUE TITLE
Prevent .cargo files getting linted. 

### ISSUE THREAD

**Issue by dgriffith0** [folke/trouble.nvim#210]
I've noticed with rust, if I do a goto definition and end up in a cargo package file, Trouble starts reporting lints in all my .cargo files Is there a way to prevent this?

**Comment by folke** [comment]
This is out of the scope of this plugin. I remember the same issue when I was developing something in Rust. I don't think I managed to fix it. Either way, the problem is with rust analyzer...

**Comment by mike-lloyd03** [comment]
@dgriffith0 Were you able to sort this out?
