### ISSUE TITLE
Expose providers/modes name

### ISSUE THREAD

**Issue by fitrh** [folke/trouble.nvim#213]
I find it is useful if we can expose the providers/modes name via a buffer variable (or anything else), so that we can show e.g. in the statusline what kind of trouble window are we in,

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
