### ISSUE TITLE
Refresh messes up current references list

### ISSUE THREAD

**Issue by uloco** [folke/trouble.nvim#214]
I usually use Trouble to walk through lsp references and so some edits there one after another. After deleting some lines my cursor usually is on another word when I enter the Trouble panel again. When I run refresh here manually, it uses the new word under cursor instead of just refreshing the view. Is there any way to prevent this / is this by design / a bug?

https://user-images.githubusercontent.com/8818340/192774160-1f9586e8-8012-4f91-8b3a-d1c8c97f547c.mov

I also often encounter trouble doing this automatically when I close folds for example and have switched between files. This is when it gets really annoying. I just want to go through all the references and make edits. Sometimes the list is very long and have to close some folds to keep track on some occurrences I want to skip.

If this is the intended behavior, do you have any way of using this workflow in another way?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
