### ISSUE TITLE
How can I make the troubles match the line of code?

### ISSUE THREAD

**Issue by jatz27** [folke/trouble.nvim#217]
I can't find how to do the same thing that is in the presentation image where the description of the trouble appears right next to the line of code that presents the error.
Thanks for your help.

**Comment by airtonix** [comment]
@jatz27 is talking about this 
![image](https://user-images.githubusercontent.com/61225/219902884-03c522ae-3e62-4bdc-b8de-a8c66b97f170.png)

I cant seem to work out how to configure this either.

**Comment by jatz27** [comment]
> @jatz27 is talking about this 
> ![image](https://user-images.githubusercontent.com/61225/219902884-03c522ae-3e62-4bdc-b8de-a8c66b97f170.png)
> 
> I cant seem to work out how to configure this either.

yes, this is what i'm talking about.

**Comment by folke** [comment]
`:h vim.diagnostic.config` You need the `virtual_text` option. This has nothing to do with trouble

**Comment by airtonix** [comment]
@jatz27 like this: 

https://github.com/airtonix/dotfiles/blob/master/devtools/files/nvim/lua/plugins/ui_syntax-lsp-errorlens.lua#L8-L10

**Comment by jatz27** [comment]
> `:h vim.diagnostic.config` You need the `virtual_text` option. This has nothing to do with trouble

Ok, I get it 
I was able to do it 
thank you so much 🙏🏼

**Comment by jatz27** [comment]
> @jatz27 like this: 
> 
> https://github.com/airtonix/dotfiles/blob/master/devtools/files/nvim/lua/plugins/ui_syntax-lsp-errorlens.lua#L8-L10

ready, thank you so much 🙏🏼
