### ISSUE TITLE
Disable one LSP from showing up in the menu

### ISSUE THREAD

**Issue by PumpedSardines** [folke/trouble.nvim#218]
Hello,
Is there a way to disable one LSP from showing up in the trouble menu. I'm currently using cspell to highlight spelling errors, however i don't want them to appear in the trouble menu. Is this currently possible to achive?

**Comment by rfortiz** [comment]
+1 I have a similar use case. 

I like to have pyright type checking as a rough guide when writing code but it generates too much noise to be enforced strictly.  An option to disable it entirely or filter the results in the aggregated list would be nice.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
