### ISSUE TITLE
Opening trouble.nvim triggers swapfile warnings

### ISSUE THREAD

**Issue by alixinne** [folke/trouble.nvim#223]
I am encountering an issue with trouble.nvim in the following situation:
- One instance of nvim has an open file, `plugins.lua` and has created a swapfile for it
- Another instance of nvim is editing another file, `preferences.lua`
- Opening any window using trouble.nvim which references locations in `plugins.lua` (the already opened file) will show the warning for when a swapfile already exists:
 
![image](https://user-images.githubusercontent.com/13561842/197621493-70d121f5-5cb4-4989-82cf-92b818983fcd.png)

I have narrowed the issue down to this function in the trouble.nvim source code:
https://github.com/folke/trouble.nvim/blob/ed65f84abc4a1e5d8f368d7e02601fc0357ea15e/lua/trouble/util.lua#L186-L200

However there may seem to be other locations where buffers are created for various items, so there is probably more relevant locations.

The issue is that `vim.uri_to_bufnr(uri)` creates a read-write buffer for the given file if it is not already opened in a buffer. Since this is being used for previews, I think the buffers should be created as readonly (such as what the `:view` command does instead of the `:edit` command), which would not trigger the warning. Then, when the user selects a location in the trouble view, the buffer would lose its readonly flag, which would trigger the warning. The user will then be able to act accordingly (recover the swapfile, discard it, etc.)

I'll try to look into it, but I do not know the Neovim Lua API well, so I'm open to suggestions on this one!

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
