### ISSUE TITLE
Lua error at multiline strings in util.lua: 'Column value outside range'

### ISSUE THREAD

**Issue by kaddkaka** [folke/trouble.nvim#224]
Warnings that refer to the position where a multiline string ends causes errors when hover in Trouble buffer and goto doesn't work.

Small example, create a python file with following content:
```py
1
"""
"""
```
To get the following warnings in the Trouble buffer:
```
   banana.py  3
 │     [pointless-statement] Statement seems to have no effect pylint (W0104) [1, 1]
 │     [pointless-string-statement] String statement has no effect pylint (W0105) [3, 0]
 │     [missing-module-docstring] Missing module docstring pylint (C0114) [1, 1]
```

When placing the cursor on the middle warning this is the error output:
```
Error executing vim.schedule lua callback: /home/david/.vim/plugged/trouble.nvim/lua/trouble/view.lua:465: Column value outside range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/david/.vim/plugged/trouble.nvim/lua/trouble/view.lua:465: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

When pressing `<enter>` on that entry, this is the error output:
```
E5108: Error executing lua /home/david/.vim/plugged/trouble.nvim/lua/trouble/util.lua:18: Column value outside range
stack traceback:
        [C]: in function 'nvim_win_set_cursor'
        /home/david/.vim/plugged/trouble.nvim/lua/trouble/util.lua:18: in function 'jump_to_item'
        /home/david/.vim/plugged/trouble.nvim/lua/trouble/view.lua:443: in function 'jump'
        /home/david/.vim/plugged/trouble.nvim/lua/trouble/init.lua:177: in function 'action'
        [string ":lua"]:1: in main chunk
```

It works fine to hover and "go to" on other warnings, it's just errors referring to last line of multiline string it seems like.

**Comment by snoord** [comment]
This issue appears when a language server publishes a [diagnostic](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic) which has an unsupported [`range.position.start.character`](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#position) value. 

In my case this diagnostic field was set to `-1` when `golangci-lint-langserver` would report specific diagnostics, usually related to the relevant file as a whole (e.g. when said file hadn't been `go fmt`ed yet).

I resolved this by attaching a custom `textDocument/publishDiagnostics` handler specifically to `golangci-lint-langserver` during the `nvim-lspconfig` setup call. The custom handler changes any `range.position.(start|end).character` value of `-1` to `0` before passing it back to the original handler:

```lua
local lspconfig = require("lspconfig")
local on_publish_diagnostics = vim.lsp.handlers["textDocument/publishDiagnostics"]
lspconfig.golangci_lint_ls.setup({
  -- <...>
  handlers = {
    -- stops an out-of-range column error when viewing diagnostics with Trouble.nvim
    ["textDocument/publishDiagnostics"] = function(_, result, ctx, config)
      for idx, diag in ipairs(result.diagnostics) do
        for position, value in pairs(diag.range) do
          if value.character == -1 then
            result.diagnostics[idx].range[position].character = 0
          end
        end
      end

      return on_publish_diagnostics(_, result, ctx, config)
    end,
  },
})
```

**Comment by siraphobk** [comment]
@snoord I just recently found this error too when using golangci-lint-ls. Your solution works flawlessly!

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
