### ISSUE TITLE
doesnt seem to work with Rust-Analyzer

### ISSUE THREAD

**Issue by Corallus-Caninus** [folke/trouble.nvim#225]
Using the standard neovim-lsp and Rust-Analyzer plugin I cannot get errors to populate the window. using stable release of current neovim in ubuntu standard repository.

**Comment by phaazon** [comment]
I reproduce but I think it’s not a problem with `trouble.nvim`, seems I have the same errors by running:

```vim
:lua = vim.diagnostic.get()
```

**Comment by phaazon** [comment]
Which version of `rust-analyzer` do you have, and do you use Mason? Try to install it as a rustup component:

```sh
rustup component add rust-analyzer
```

And then compare the version with:

```sh
~/.share/local/nvim/mason/bin/rust-analyzer
rustup run stable rust-analyzer
```

The mason one is lagging like forever behind.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
