### ISSUE TITLE
Remove duplicates

### ISSUE THREAD

**Issue by AdamJSoftware** [folke/trouble.nvim#231]
Hello!

Great project, but one minor annoyance (might be something on my end but I still feel that it can be easily addressed here) is the fact that I have multiple of the same errors duplicate. Here is a screenshot below

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/42972871/202233056-4b7e4348-8aff-4955-b4f4-9ef358e40b67.png">

Is there any way to automatically remove these duplicates?

**Comment by xero** [comment]
do you have multiple lsp servers attached to the same buffer, each spitting out an error? that sounds more like the actual issue here.

**Comment by ilourt** [comment]
I have the same problem.

If I stop my lsp server (I check there is no more process of it running on my machine) the messages remain in trouble.
When I start again my LSP all messages are duplicated. Each time I restart my lsp there is a new line for each message.

I tried to refresh trouble with `r`and `:TroubleRefresh` but these commands do nothing.

Do you have any idea how to correct this?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
