### ISSUE TITLE
highlight group selected item line

### ISSUE THREAD

**Issue by uloco** [folke/trouble.nvim#234]
I am creating a theme and the selected item in the list currently is the same color as `CursorLine` but I want to have a different background for trouble then the default normal background.

So how can I theme the currently selected line in the trouble window?

**Comment by folke** [comment]
There is no selected item highlight.
That is default Neovim behavior to show the current line with `CursorLine`.

So yes, it is by design the same as `CursorLine`.

**Comment by uloco** [comment]
Would it be possible to add a custom highlight group and link it as a default to CursorLine, so that it is possible to be themed by others? Because currently I cannot do anything abou this.
