### ISSUE TITLE
Troubletoggle generates Error while opening.

### ISSUE THREAD

**Issue by akashdiphazra** [folke/trouble.nvim#236]
```lua
lvim.builtin.which_key.mappings["t"] = {
  name = "Diagnostics",
  t = { "<cmd>TroubleToggle<cr>", "trouble" },
  w = { "<cmd>TroubleToggle workspace_diagnostics<cr>", "workspace" },
  d = { "<cmd>TroubleToggle document_diagnostics<cr>", "document" },
  q = { "<cmd>TroubleToggle quickfix<cr>", "quickfix" },
  l = { "<cmd>TroubleToggle loclist<cr>", "loclist" },
  r = { "<cmd>TroubleToggle lsp_references<cr>", "references" },
}
```

[202669726-99ae744b-539d-4d0d-a68b-c2a31abadb19.webm](https://user-images.githubusercontent.com/61003681/203377031-469736bb-59fb-48ea-a3cb-fa1089f88e9f.webm)

**Comment by RasmusFangel** [comment]
I'm just playing around with (vim, neovim and) LunarVim for the first time and I had the same problem. I don't think it has anything to do with this plugin but the lvim config. Try adding 

```lua
lvim.plugins = {
  {"folke/trouble.nvim"}
}
```

Right about your mapping and run `:PackerSync` afterwords and restart lvim.

Let me know if it works for you, it did the trick for me.

**Comment by carlosonrails** [comment]
I did exactly what U say and same behavior here. Any clue how to solved it?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
