### ISSUE TITLE
Feature request: Only open non-selected Telescope results

### ISSUE THREAD

**Issue by Hubro** [folke/trouble.nvim#237]
Trouble can receive selected items from Telescope by using `open_selected_with_trouble` or `smart_open_with_trouble`, but there is currently no way to do the opposite, i.e. only open non-selected results.

This would come in handy when opening a large number of results, for example from `:Telescope live_grep`, where only a few of the results are "bad". I could select every result except the 1-2 results I don't want, but it would be much less effort to only select the ones I don't want to open.

I currently have `<C-q>` bound to open results in Trouble. I would love to be able to bind `<C-Q>` (<kbd>Ctrl</kbd><kbd>Shift</kbd><kbd>q</kbd>) to open non-selected items.

**Comment by Hubro** [comment]
Well damn, I just checked the source code in case this was something I could add a PR for, and I found `open_selected_with_trouble` and `smart_open_with_trouble` :laughing: 

I guess I'll rename the feature request and reduce the scope to "ability to open non-selected results".

**Comment by folke** [comment]
that's too specific
