### ISSUE TITLE
Closing Trouble does not refocus last window.

### ISSUE THREAD

**Issue by sharpenedblade** [folke/trouble.nvim#240]
### Description
When closing the trouble window, focus does not go back to where the cursor was before opening trouble. 

### Steps to Reproduce:
1. Open 2 windows with `:vsplit` or `:split`
2. Move focus/cursor to the right/top.
3. Open the trouble window
4. press `q`

### What should happen:
Focus returns to the right/top window you were previously in.

### What currently happens:
Focus will return to the bottom left window.

### Additional information:
This happens with any window, not just splits with regular buffers. I tested and it also happens with `NvimTree` windows, and should happen with anything else.

**Comment by farukara** [comment]
came to open the same issue and saw that one. While here, thanks for making such a great plugin.

The away I experience it is, my nvim_tree is almost always open, and when I quit the trouble, it always jumps to nvim_tree buffer, which is not desired. I want it to go back to where I came from if that's possible at all. 

Thanks.

**Comment by braxtons12** [comment]
Also experiencing this and it's rather annoying.

**Comment by PeterGoedeke** [comment]
Same issue here.
