### ISSUE TITLE
[Question] In the README's first image, how the red and yellow diagnostic wavy lines are configured?

### ISSUE THREAD

**Issue by Fau818** [folke/trouble.nvim#241]
In the following image, how the red and yellow diagnostic wavy lines are configured?

 It does not seem to be configured by the plugin.

![shot](https://user-images.githubusercontent.com/75115028/208664462-106e432b-2890-4462-b82f-4a50b9caf9bb.png)

**Comment by folke** [comment]
You need a terminal like [kitty](https://github.com/kovidgoyal/kitty) that supports undercurls

**Comment by Fau818** [comment]
Sorry to bother you again. What is the name of the font used in the image? I really like it.

**Comment by folke** [comment]
```
font_family      FiraCode Nerd Font
bold_font        Fira Code Bold Nerd Font Complete
italic_font      Victor Mono Medium Italic Nerd Font Complete
bold_italic_font Victor Mono Bold Italic Nerd Font Complete
```
