### ISSUE TITLE
bug: folke/trouble.nvim installation problems not identified in :checkhealth

### ISSUE THREAD

**Issue by dstromberg** [folke/trouble.nvim#245]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.1

### Operating system/version

macOS 12.6

### Describe the bug

Trouble silently fails to install itself with LunarVim, and there is nothing relevant in :checkhealth.

This bleeds over to a feature request: It'd be great for your users, and probably for you too, if Trouble could surface problems in the checkhealth report.

I'm getting no :Trouble command:
E492: Not an editor command: Trouble

I've tried it (so far) with bashls and sumneko_lua.  Intentionally introducing a syntax error in either produces no Trouble report.

I've currently got this (among other things) in my config.lua:
  return packer.startup(function(use)                                                                                                  
  │   use {                                                                                                                                                                                   
  │   │   'wbthomason/packer.nvim' -- Have packer manage itself                                                                                                                               
  │   }                                                                                                                                                                                       
  --     use {                                                                                                                         
  --         'ilAYAli/scMRU.nvim' -- This is to give an :Mru command, which is per-git-repo unlike ygappan/mru                         
  --     }                                                                                                                             
  │   use {                                                                                                                                                                                   
  │   │   'ibhagwan/fzf-lua',                                                                                                                                                                 
  │   │   requires = { 'nvim-tree/nvim-web-devicons' }                                                                                                                                        
  │   }                                                                                                                                                                                       
  │   use {                                                                                                                                                                                   
  │   │   "folke/trouble.nvim",  -- Gives a subwindow of errors at the bottom                                                                                                                 
  │   │   requires = { "kyazdani42/nvim-web-devicons", "folke/lsp-colors.nvim" },                                                                                                             
  │   │   config = function()                                                                                                                                                                 
  │   │   │   require("trouble").setup {                                                                                               
  │   │   │   │   -- your configuration comes here                                                                                     
  │   │   │   │   -- or leave it empty to use the default settings                                                                     
  │   │   │   │   -- refer to the configuration section below                                                                          
  │   │   │   │   height = 7                                                                                                           
  │   │   │   }                                                                                                                        
  │   │   end                                                                                                                          
  │   }                                                                                                                                
  │   end                                                                                                                              
  )

### Steps To Reproduce

1. Install LunarVim, either by using the official LunarVim installer, or you can see exactly what I have by svn checkout'ing https://stromberg.dnsalias.org/svn/lunarvim-config/trunk and running "make install".  My full config.lua is there too, at https://stromberg.dnsalias.org/svn/lunarvim-config/trunk/config-lvim/config.lua
2. Enter LunarVim with the 'lvim filename' command
3. Try to issue the :Trouble command, and see that it doesn't tab-complete or appear as an editor command.

### Expected Behavior

I want to see Trouble's report of errors at the bottom of my LunarVim session.

### Repro

```Lua
Covered above.
```

**Comment by folke** [comment]
must be due to laz-loading in lunarvim. not a trouble issue
