### ISSUE TITLE
feature: Set option to order list by line number instead of severity

### ISSUE THREAD

**Issue by steakhutzeee** [folke/trouble.nvim#247]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

No.

### Describe the solution you'd like

From the docs i have not found a solution on how to order the list per line number instead of severity.

### Describe alternatives you've considered

N/A

**Comment by unphased** [comment]
Yeah. sometimes I want to pull up a list of all the diags in a visible region in the code and the severity based sort makes this hard to do.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by unphased** [comment]
Incredible!

Btw I use Trouble just as much, if not more for browsing references than for diags. The automated buffer view behaviors are just so perfect.
