### ISSUE TITLE
bug: Cursor position outside buffer in Telescope

### ISSUE THREAD

**Issue by kiyoon** [folke/trouble.nvim#250]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.2

### Operating system/version

Ubuntu 22.04

### Describe the bug

![image](https://user-images.githubusercontent.com/12980409/213319520-d340e3aa-a44d-4ca6-9d91-758c63fa7438.png)

I think the plugin doesn't understand where the files actually are. It doesn't open it properly with this error message.

### Steps To Reproduce

I think it happens when the cwd from the Telescope args has changed, or using `builtin.git_files`

```lua
-- get git folder
local function get_git_dir()
  local git_dir = vim.fn.trim(vim.fn.system "git rev-parse --show-toplevel")
  return git_dir
end

local builtin = require "telescope.builtin"

M = {}
M.live_grep_gitdir = function()
  local git_dir = get_git_dir()
  if git_dir == "" then
    builtin.live_grep()
  else
    builtin.live_grep {
      cwd = git_dir,
    }
  end
end

```

### Expected Behavior

It should read the actual file path and find the files correctly. Maybe trouble is assuming a default cwd.

**Comment by kiyoon** [comment]
Thanks for the quick fix!

**Comment by varunbpatil** [comment]
@folke the fix (https://github.com/folke/trouble.nvim/commit/3174767c61b3786e65d78f539c60c6f70d26cdbe) breaks telescope LSP references -> Trouble for golang. Had to revert to trouble v1.0.0

**Comment by folke** [comment]
@varunbpatil what is the error you get? Need to know how exactly to fix this. Not going to install golang for this

**Comment by folke** [comment]
Can reproduce with lua. will fix

**Comment by folke** [comment]
@varunbpatil should be fixed now

**Comment by varunbpatil** [comment]
Thanks @folke . Can confirm that it is working with golang too.
