### ISSUE TITLE
bug: diagnostics from quickfix is not working

### ISSUE THREAD

**Issue by lonnywong** [folke/trouble.nvim#257]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-8fbe75b

### Operating system/version

Ubuntu 22.04

### Describe the bug

`:Trouble` shows the errors from quickfix, but no diagnostics shows in the source code.

### Steps To Reproduce

1. `nvim test.c`, the source content:
```c
int main() {
  return "";
}
```

2. `:w`

3. `:PackerSync`

4. `:make`

### Expected Behavior

Shows diagnostics as virtual text in the source code.

### Repro

```Lua
require('packer').startup(function(use)
    use 'wbthomason/packer.nvim'
    use 'neovim/nvim-lspconfig'
    use {
       "folke/trouble.nvim",
       requires = "nvim-tree/nvim-web-devicons",
       config = function()
       require("trouble").setup {
          mode = "quickfix",
       }
    end
    }
end)

vim.o.makeprg = 'gcc test.c'
```

**Comment by folke** [comment]
Trouble does not add virtual text

**Comment by lonnywong** [comment]
> Trouble does not add virtual text

Thanks for pointing it out.

Could you add a feature for it?

**Comment by folke** [comment]
No

**Comment by lonnywong** [comment]
That's OK. Thanks anyway.
