### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [folke/trouble.nvim#266]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.0-dev-903+gecc40660d

### Operating system/version

Windows 10

### Describe the bug

Trouble does not update errors after they are fixed. in vue sfc.

### Steps To Reproduce

1. I have a pinia store that just returns `useSomethingStore`
2. I added a property to the state of the store
3. When I try to access that property now, trouble says it does not exist in the store

### Expected Behavior

There should be a check when some reference changes.
There should be a way to force a reevaluation of trouble errors.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")
-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's not a Trouble issue. Trouble just shows diagnostics. So you'll have to check the config of your lsp server

**Comment by sschneider-ihre-pvs** [comment]
gotcha
