### ISSUE TITLE
help: theming [Quickfix \ Total : X]

### ISSUE THREAD

**Issue by GiuseppeMP** [folke/trouble.nvim#267]
Hey guys,

I'm using Trouble with [rose-pine](https://github.com/rose-pine/neovim) theme, and I'm trying to change the highlight of count next to the Trouble icon, but without success, see image below (`bg` grey and `fg` fading red, it's a kind hard to see).

<img width="264" alt="image" src="https://user-images.githubusercontent.com/4944009/224079709-2f4960c3-87b7-4621-beaf-fe1d2823717b.png">

I tried `TroubleCount` and others groups of the documentation but none of them affected this region.

Ty all.

**Comment by folke** [comment]
Where is that displayed? That's not Trouble, but a statusline component?

**Comment by GiuseppeMP** [comment]
@folke You are right! I found https://github.com/windwp/windline.nvim/blob/master/lua/wlsample/evil_line.lua#L127.

It's a default integration of [windline](https://github.com/windwp/windline.nvim) for Trouble, sorry for opening an issue here, the Trouble icon misleads me.
