### ISSUE TITLE
feature: multiline error messages in the error browser

### ISSUE THREAD

**Issue by teleyos** [folke/trouble.nvim#268]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

when using with typescript i have massive errors (2-3 lines) and they aren't fully displayed
![image](https://user-images.githubusercontent.com/56928284/224621682-c220480e-be5d-4cb7-845a-15ab6ab92d8c.png)

### Describe the solution you'd like

I'd like a way to say to the plugin that I allow line wrap or give more character to see the full error message

### Describe alternatives you've considered

I have to launch the file in vscode to see the full error

**Comment by folke** [comment]
You can use `K` to see the full error. Not planning on adding any other type of functionality for this.
