### ISSUE TITLE
feature: support dressing ui

### ISSUE THREAD

**Issue by linrongbin16** [folke/trouble.nvim#269]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Hi, can we support dressing ui? instead of only bottom/top/left/right.

### Describe the solution you'd like

support dressing ui instead of only bottom/top/left/right.

### Describe alternatives you've considered

there are several ui library: dressing, noice, nui, etc. please support them.

**Comment by folke** [comment]
Your request makes no sense. dressing.nvim overrides input  & select. Noice.nvim is something entirely different.

So no

**Comment by linrongbin16** [comment]
hi, what about floating window?

**Comment by folke** [comment]
Neither dressing.nvim, not noice.nvim expose API's or integration points for other plugins to provide floating windows.

I'm not interested in adding a floating window ui to trouble

**Comment by linrongbin16** [comment]
Thanks for reply.
