### ISSUE TITLE
bug: Wrong readings

### ISSUE THREAD

**Issue by AndreM222** [folke/trouble.nvim#270]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [x] I have searched the exsiting issues of plugins related to this issue

### Neovim version (nvim -v)

0.8.3

### Operating system/version

Windows 11

### Describe the bug

I dont know if this is what it should be doing but when I try to run it it starts reading the files located where nvim was installed instead of the current file I am at.
![image](https://user-images.githubusercontent.com/98118238/226071371-f5d76625-3318-4882-bc57-acefb605ce74.png)
that is one of the places its loading but my lcoation is this
![image](https://user-images.githubusercontent.com/98118238/226071406-5d0aecba-c032-477f-b7bd-db15bfa1b91c.png)

### Steps To Reproduce

Just normal setup.
run troubletoggle workspace_diagnostics

### Expected Behavior

Just load the current workspace. not where nvim was installed

**Comment by folke** [comment]
Trouble just shows diagnostics. If you think those are incorrect, then you need to fix your lsp.

**Comment by AndreM222** [comment]
Okay I will take a look. Great job in all your plugins

**Comment by AndreM222** [comment]
You are right. I am sorry and awesome work bro. keep it up
