### ISSUE TITLE
feature: Trouble opens in a floating window

### ISSUE THREAD

**Issue by lukiliuk** [folke/trouble.nvim#273]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to have every plugin i use in floating mode, so the screen is always as clean as possible

### Describe the solution you'd like

TroubleToggle opens in a floating window, instead just left,right,bottom and top, much like telescope or toggleterm

### Describe alternatives you've considered

nothing else i considered

**Comment by Diablo-D3** [comment]
I think more generally, we should be able to pass the config table usually sent to `nvim_win_set_config`.

I currently use a hack that uses `autocmd` to achieve this, and I can't say I'm 100% happy with it.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
