### ISSUE TITLE
bug: Default loclist

### ISSUE THREAD

**Issue by tororutsu** [folke/trouble.nvim#276]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0-dev-36+g7ffe45017

### Operating system/version

Void Linux

### Describe the bug

I want to disable the default loclist that pops up and replace it with Troubles.
![image](https://user-images.githubusercontent.com/20189326/232314763-6c46d209-1c20-41c0-a2f3-3d1ffb78f5be.png)

### Steps To Reproduce

1. Install trouble
2. Save code
3. Default Loclistshows up not trouble

### Expected Behavior

I want Troubles loclist to be the default

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by marcoSven** [comment]
I am having the same issue
