### ISSUE TITLE
feature: I want the diagnostic area to be rendered like markdown.

### ISSUE THREAD

**Issue by saying121** [folke/trouble.nvim#280]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

nothing

### Describe the solution you'd like

current：
![now](https://github.com/folke/trouble.nvim/assets/74663483/fe20d5db-dc48-469e-a37f-cd8192c0a2b1)

I want：
![want](https://github.com/folke/trouble.nvim/assets/74663483/36c5e161-35f7-4e82-9e19-80b815eed37e)

### Describe alternatives you've considered

nothing

### Additional context

nothing

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
