### ISSUE TITLE
feature: Add a setting to show the current severity filter

### ISSUE THREAD

**Issue by MariaSolOs** [folke/trouble.nvim#301]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

When switching the severity filter in the diagnostics list, it would be really useful to have some kind of label indicating the current filter, since in some cases the list might be empty and it's impossible (?) to tell which filter is currently being applied.

### Describe the solution you'd like

A label somewhere in the diagnostics panel, or even a way to get this information so that one can apply it in the status line or somewhere else.

### Describe alternatives you've considered

Accept the sad truth that this might be a lower priority issue :(

**Comment by eatgrass** [comment]
@folke maybe we can show some extra infomation based on the provider currently in used in the padded line?

**Comment by MariaSolOs** [comment]
Closing as this way fixed with #304.
