### ISSUE TITLE
bug: Opening Trouble crashes Neovim

### ISSUE THREAD

**Issue by MariaSolOs** [folke/trouble.nvim#303]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0-dev-629+gb2e8c0df2

### Operating system/version

Mac Ventura 13.4.1

### Describe the bug

When opening `Trouble` on nightly, Neovim crashes and a "Process exited with error code 134" error is displayed in the terminal.

### Steps To Reproduce

1. Open any file with the latest nightly release of Neovim.
2. Open Trouble.

### Expected Behavior

For Trouble (and Neovim) to not crash :)

**Comment by MariaSolOs** [comment]
After several hours of debugging, I discovered that this was caused by my [folding ranges](https://github.com/MariaSolOs/dotfiles/blob/aeb82faaf25bd167283c47f684ef9ec7c7c27370/.config/nvim/lua/plugins/ufo.lua) configuration. Adding `ft_ignore = { 'trouble' }` to my `statuscol` settings fixed, although I'm quite confused as to what changed, since I haven't recently updated those extensions...

**Comment by folke** [comment]
Plugins can't really crash Neovim, that's always due to bugs in Neovim itself. So maybe due to a recent Neovim change?

**Comment by MariaSolOs** [comment]
> Plugins can't really crash Neovim, that's always due to bugs in Neovim itself. So maybe due to a recent Neovim change?

Yeah, I can only reproduce it on nightly when `statuscol` is enabled.

**Comment by MariaSolOs** [comment]
I’m now paranoid of this mysterious issue appearing again :(
