### ISSUE TITLE
Semantic highlight gets messed up when used with ccls + vim-lsp-cxx-highlight

### ISSUE THREAD

**Issue by Badhi** [folke/trouble.nvim#31]
I'm trying to use this plugin on c++ development which uses `ccls` as the language server and [vim-lsp-cxx-highlight](https://github.com/jackguo380/vim-lsp-cxx-highlight) as the plugin that does the semantic highlighting.

When I get the all references of some function through `TroubleToggle lsp_references` it pops up a separate buffer giving the correct occurrences accurately. Also I can hover through the suggestions where it opens up temporary buffers displaying the files. But when I quit the list I could observe all the highlights on the original file which I started with is all messed up

I'm not entirely sure if this is an issue in this plugin or the lsp cxx highlight plugin.

**Comment by folke** [comment]
Can you post a screenshot of what you mean?

**Comment by Badhi** [comment]
Sure,

![trouble](https://user-images.githubusercontent.com/10277051/118513429-53237a00-b751-11eb-93ba-877a42b2020e.gif)

Here you can see before and after I called `Trouble`, some of the highlights are missing. Also, the LSP status section on the airline status line is missing. Maybe I'm not "exiting" the Trouble mode correctly leaving it in some intermediate state. Please let me know if I'm doing something wrong here

I'm using the following setup config
```
require("trouble").setup {
    action_keys = { -- key mappings for actions in the trouble list
        close = "q", -- close the list
        cancel = "<esc>", -- cancel the preview and get back to your last window / buffer / cursor
        refresh = "r", -- manually refresh
        jump = {"<cr>", "<tab>"}, -- jump to the diagnostic or open / close folds
        jump_close = {"o"}, -- jump to the diagnostic and close the list
        toggle_mode = "m", -- toggle between "workspace" and "document" diagnostics mode
        toggle_preview = "P", -- toggle auto_preview
        hover = "K", -- opens a small poup with the full multiline message
        preview = "p", -- preview the diagnostic location
        close_folds = {"zM", "zm"}, -- close all folds
        open_folds = {"zR", "zr"}, -- open all folds
        toggle_fold = {"zA", "za"}, -- toggle fold of current file
        previous = "k", -- preview item
        next = "j" -- next item
    },
    signs = {
        Errors = '',
        Warnings = '',
        Info = '',
        Hint = '',
        Other = '',
    },
    use_lsp_diagnostic_signs = false,
}
```

**Comment by folke** [comment]
Right. After it's messed up and when you press ctrl-l, it fixes itself probably?

It's a known neovim Unicode incompatibility (terminal and vim don't agree on the width of some Unicode characters) I have that as well with kitty.

There's a couple of bug reports both in the neovim repo and the kitty repo. Nothing I can do about it I'm afraid.

You can try configuring the icons in trouble to different ones. Pure ASCII icons won't trigger this issue.

**Comment by Badhi** [comment]
Ctrl+L doesn't fix it, but if I switch buffer with Ctrl+6 twice it gets fixed. Thanks for the info, will give it some try.

**Comment by folke** [comment]
closing this, since it's unrelated to trouble. Thank you for reporting!
