### ISSUE TITLE
[Feature] Only display certain LSP servers in the workspace diagnostic panel

### ISSUE THREAD

**Issue by pidgeon777** [folke/trouble.nvim#315]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Sometimes, multiple LSP servers are active in a workspace.

This could for example happen when editing a LUA and a C/C++ project.

In this case, Trouble would report all errors coming from both the C and LUA LSP servers, which could be annoying when one would want to focus on just one project, because the diagnostic panel would be over-populated with the found issues coming from all of the active LSP servers.

### Describe the solution you'd like

It could be good to add an argument/option to the `Trouble workspace_diagnostics` function so that a table of strings can be passed to it specifying the name of the LSP servers to be reported in the workspace diagnostic panel.

For example:

`Trouble workspace_diagnostics reported_lsp={ "clangd", "sumneko_lua" }

Or, more in general, a functionality which lets the user dynamically filter out the unwanted LSP servers from an active workspace diagnostic panel (for example with checkboxes).argument/option

### Describe alternatives you've considered

N/A

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
