### ISSUE TITLE
Feature request: possibility of different grouping

### ISSUE THREAD

**Issue by echasnovski** [folke/trouble.nvim#33]
Currently, when using with 'trouble.nvim' all found keyword comments are grouped by file. I often find myself wanting to look only at all TODOs. I can do that by unfolding everything and using built-in search, but it is a bit troublesome. Maybe there is a way to incorporate different grouping? So that folds represent different keywords and not files. Maybe a keymapping inside Trouble window?

Or is it better to open this issue in 'trouble.nvim'?

Command I am currently using: `TroubleToggle todo`.

**Comment by folke** [comment]
I've thought about this as well. I think I'll add an option to change the grouping like you mention:
* group by file (default)
* group by type (diagnostics severity, todo keyword, ,...)

I'll add it to the list

**Comment by echasnovski** [comment]
Maybe it can be not a plugin option but something that can be picked by user in runtime? So by default it opens with file grouping but can be switched to type grouping and back.

**Comment by folke** [comment]
@echasnovski yep, that's what I had in mind

**Comment by tom-anders** [comment]
Any update on this? I'd also find it useful to have nested folds (e.g. First level could be grouped by module/folder, second level by file).

**Comment by folke** [comment]
With Trouble v3, this is finally possible! :)

The docs on this are still a bit lacking, but you can check out the builtin sources on how to change the groups and formats

**Comment by echasnovski** [comment]
Huzzah! Almost three years later!
