### ISSUE TITLE
Question: LSP References Icons

### ISSUE THREAD

**Issue by ashton** [folke/trouble.nvim#332]
Is there a way of customizing LSP references icons?

Currently they all show as a bell icon, but would be nice if we could use something like [lsp-kind](https://github.com/onsails/lspkind.nvim) icons
![image](https://github.com/folke/trouble.nvim/assets/95974/687633d6-841d-446c-b74d-3e98810957da)

**Comment by vanguard-bit** [comment]
`https://github.com/folke/trouble.nvim?tab=readme-ov-file#setup`
`    signs = {
      -- icons / text used for a diagnostic
      error = "",
      warning = "",
      hint = "",
      information = "",
      other = "",
    },
`
change this to whatever you want....
I dont know about kind icons tho

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
