### ISSUE TITLE
bug: trouble quickfix takes ghostly control of cursor

### ISSUE THREAD

**Issue by Amleto** [folke/trouble.nvim#336]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

win10 22h2

### Describe the bug

executing `trouble.open("quickfix")` and putting the cursor under the trouble group results in the cursor moving by itself. It moves one column at a time to the right until it reaches the end of the line, then it goes to the next line, starting at the first column. This repeats until it reaches the last column of the last line.

Additionally the theme is broken and the main buffer is replaced with a second trouble buffer.
From this,
![image](https://github.com/folke/trouble.nvim/assets/2996796/92e7eb22-61bd-4a03-be6c-b51a8214af1b)

To this,
![image](https://github.com/folke/trouble.nvim/assets/2996796/52e1a46e-3a91-4539-973a-8787e5e989a0)

### Steps To Reproduce

1. install cmake and put on PATH
2. install clang/clangd and put on PATH
3. clone the c++ test repo ([gist](https://gist.github.com/Amleto/0ce63d8ef841e1d63510917004a2e697))
4. In the test repo run `nvim -u repo.lua`
5. `:CMakeSelectConfigurePreset` - choose default
6. `:CMakeGenerate` 
7. `:CMakeBuild` (choose ALL_BUILD if necessary)

There should be build errors - check with `:cope`, then close them :`ccl`
8. `:lua require'trouble'.open'quickfix'`
9. `<CR>` to ignore the missing web-devicons warning
10. Watch the cursor take control of itself.

### Expected Behavior

The trouble quickfix buffer should open, the cursor should not go crazy, and the already-open buffer should not have its content replaced.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
  {
    "Civitasv/cmake-tools.nvim",
    dependencies ={"nvim-lua/plenary.nvim"},
  }
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by Amleto** [comment]
https://github.com/folke/trouble.nvim/assets/2996796/2f6e8c52-6e8e-43ea-be52-a30a7a93c4c1

screen recording of the phenomenon

**Comment by YodaEmbedding** [comment]
See also:

- https://github.com/folke/trouble.nvim/issues/87

**Comment by Amleto** [comment]
Thanks @YodaEmbedding for highlighting previous reports, and thanks @folke for the plug-in and the fix
