### ISSUE TITLE
Missing help page

### ISSUE THREAD

**Issue by languitar** [folke/trouble.nvim#34]
It would be nice if there was a vim help page for this plugin.

**Comment by folke** [comment]
I'm not planning on maintaining two document sources. The github readme contains all the info to use Trouble. If you believe something is missing, let me know.

**Comment by languitar** [comment]
Ah. Nothing is missing. It was just unexpected to not find anything with `:h Trouble`.

**Comment by lewis6991** [comment]
I agree. A help page is a must for any good plugin. The README and the vim doc really serve different purposes even if they contain overlapping information.
