### ISSUE TITLE
feature: readme examples for lua toggle instead of `open`

### ISSUE THREAD

**Issue by davidgamero** [folke/trouble.nvim#340]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

when using the configs from the README, the lua examples don't toggle, while the vim script ones do

### Describe the solution you'd like

offer a new set of lua example keymaps that do allow toggling, or update the existing ones to do so since i don't think it's an issue to add toggle when the current just opens (and does nothing once trouble is open)

### Describe alternatives you've considered

putting a link to how to implement this yourself, but that is less user-friendly

**Comment by folke** [comment]
Just replace `open` with `toggle` and you're good to go.
I've also updated the docs.

**Comment by davidgamero** [comment]
Tysm!
