### ISSUE TITLE
bug: icons not showing and duplicate windows possible

### ISSUE THREAD

**Issue by Joywatchin** [folke/trouble.nvim#341]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.2

### Operating system/version

Macos 14.0

### Describe the bug

When I try and open Trouble, I run into a problem of having an icon-less diagnostics window. Then, if I try and toggle Trouble again, the correct window pops up below the faulty initial window.
<img width="1440" alt="help" src="https://github.com/folke/trouble.nvim/assets/67507794/e67e9915-bb6f-4b03-9694-012edbee7b7f">

### Steps To Reproduce

1. Installed on nvchad using a custom plugins file as shown below
<img width="877" alt="image" src="https://github.com/folke/trouble.nvim/assets/67507794/2fa97589-3f2a-453b-8fb5-035be10733a0">
2. Added a keybind to the custom init file (from the docs)
<img width="1018" alt="image" src="https://github.com/folke/trouble.nvim/assets/67507794/b785311d-ab9c-46af-8df9-593b89799c39">
3. Go to a python project with errors and press space then q
4. Press space then q again

https://github.com/folke/trouble.nvim/assets/67507794/b47128bf-088d-4097-8b9a-08575a266dc3

### Expected Behavior

It should open the diagnostic window WITH icons and be able to close with the same key (space and q)

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
