### ISSUE TITLE
feature: order inline diagnostics by severity

### ISSUE THREAD

**Issue by ianschmitz** [folke/trouble.nvim#360]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I would like to see error level diagnostics before warning level diagnostics in the in-line view when both are present on the same line number.

For example:
![CleanShot 2023-11-18 at 16 05 18@2x](https://github.com/folke/trouble.nvim/assets/6355370/e73f43de-93da-44e4-9eda-c19d5aca1d2a)

### Describe the solution you'd like

Display the diagnostics such that error level diagnostics show up first before warning level.

### Describe alternatives you've considered

Hiding warning level diagnostics

### Additional context

Sorry if this is a dumb question or already supported in some way. There wasn't an obvious solution in the docs from what i saw. 

I'm a neovim/LazyVim noob but trying to learn!

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
