### ISSUE TITLE
bug: column value outside of range

### ISSUE THREAD

**Issue by RomaLzhih** [folke/trouble.nvim#364]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Centos 8

### Describe the bug

When I move within trouble pane, it throws an error message as follows:

![Weixin Screenshot_20231207134927](https://github.com/folke/trouble.nvim/assets/45626759/6e55e23e-6f08-4d00-afb9-a5bcfb40be00)

### Steps To Reproduce

I use Nvchad as distribution and add following code in `custom/plugins`:
```{lua}
{
 "folke/trouble.nvim",
 dependencies = { "nvim-tree/nvim-web-devicons" },
 opts = {
  -- your configuration comes here
  -- or leave it empty to use the default settings
  -- refer to the configuration section below
 },
}
```

### Expected Behavior

No error message shows.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
