### ISSUE TITLE
bug: `use_diagnostic_signs = true` no longer works due to a recent Neovim change (0.10+)

### ISSUE THREAD

**Issue by xfzv** [folke/trouble.nvim#369]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-1856+gf4f7e2946-dirty

### Operating system/version

Gentoo Linux

### Describe the bug

Due to a recent change in Neovim (https://github.com/neovim/neovim/pull/26193 I believe), [diagnostics signs are now configured differently](https://github.com/neovim/neovim/blob/8122470f8310ae34bcd5e436e8474f9255eb16f2/runtime/doc/diagnostic.txt#L438-L447).

As a result, trouble displays "E" ; "W" ; "H" ; "I" letters instead of respective configured signs, despite using `use_diagnostic_signs = true`.

### Steps To Reproduce

- trouble config:

```lua
return {
  "folke/trouble.nvim",
  cmd = { "Trouble", "TroubleToggle" },
  dependencies = "nvim-tree/nvim-web-devicons",
  opts = {
    use_diagnostic_signs = true, -- Use the signs already defined in LSP
  },
}
```

- `neovim/nvim-lspconfig` config:

```lua
return {
  "neovim/nvim-lspconfig",
  event = { "BufReadPre", "BufNewFile" },
  config = function()
    vim.diagnostic.config({
      signs = {
        text = {
          [vim.diagnostic.severity.ERROR] = " ",
          [vim.diagnostic.severity.WARN] = " ",
          [vim.diagnostic.severity.INFO] = " ",
          [vim.diagnostic.severity.HINT] = " ",
        },
      },
    })
  end,
}
```

1. Using Neovim nightly, trigger a diagnostic in any file
2. The diagnostic sign is correctly displayed in the SignColumn
3. Open trouble with `:Trouble`
4. The default letter is displayed in trouble instead of the configured sign:
![image](https://github.com/folke/trouble.nvim/assets/78810647/6842063c-5c39-4900-84dc-13cd459b8bdc)

### Expected Behavior

trouble displays signs instead of letters

**Comment by gpanders** [comment]
Note that with https://github.com/neovim/neovim/pull/26618, https://github.com/neovim/neovim/pull/26193 is no longer a breaking change. Plugins should still migrate to the new configuration format, but there is no immediate need to do so.

**Comment by suliatis** [comment]
I have a neovim config only using the new way to define diagnostic signs, so I decided to fix this by myself. You can see my pr above. Feel free to checkout and give your feedback.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by fgr1986** [comment]
Dear @folke  is it possible that it is not yet enabled on `dev` branch? (I still see the E/W letters instead of icons).

Thanks

**Comment by folke** [comment]
Trouble now always uses the configured Neovim diagnostic signs.

**Comment by fgr1986** [comment]
I configured neovim diagnostics, but somehow they are not picked up (just moved to `dev` today)
![image](https://github.com/folke/trouble.nvim/assets/10627849/99eda310-4abb-4aba-807f-58be96a58af2)

**Comment by folke** [comment]
Did you use `vim.diagnostic.config`? And not `sign_define`? sign_define is deprecated

**Comment by fgr1986** [comment]
No, could find that in the dev docs.
Could you point me there?

In the lsp handlers I have
`vim.diagnostic.config(lsp.diagnostic)`

**Comment by folke** [comment]
Can you show me the exact table you pass to diagnostics config?

**Comment by fgr1986** [comment]
Interestingly, everything works on 
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1713773202, 

but it fails on 
NVIM v0.10.0-dev Build type: RelWithDebInfo, LuaJIT 2.1.0-beta3.

The table you asked for:

`local M = {}

function M.setup()
  -- LSP handlers configuration
  local lsp = {
    float = {
      focusable = true,
      style = "minimal",
      border = "rounded",
    },
    diagnostic = {
      -- virtual_text = true,
      virtual_text = { spacing = 4, prefix = "●" },
      underline = true,
      update_in_insert = false,
      severity_sort = true,
      float = {
        focusable = true,
        style = "minimal",
        border = "rounded",
      },
    },
  }

  -- Diagnostic signs
  local diagnostic_signs = {
    {
      name = "DiagnosticSignError",
      text = ""
    },
    {
      name = "DiagnosticSignWarn",
      -- text = ""
      text = ""
    },
    {
      name = "DiagnosticSignHint",
      text = ""
    },
    {
      name = "DiagnosticSignInfo",
      text = ""
    },
  }
  for _, sign in ipairs(diagnostic_signs) do
    vim.fn.sign_define(sign.name, { texthl = sign.name, text = sign.text, numhl = sign.name })
  end

  -- Diagnostic configuration
  vim.diagnostic.config(lsp.diagnostic)

  -- Hover configuration
  vim.lsp.handlers["textDocument/hover"] = vim.lsp.with(vim.lsp.handlers.hover, lsp.float)

  -- Signature help configuration
  vim.lsp.handlers["textDocument/signatureHelp"] = vim.lsp.with(vim.lsp.handlers.signature_help, lsp.float)
end

return M
`

**Comment by folke** [comment]
like I said, on `0.10`, you need to pass `signs` as an option to `vim.diagnostic.config`. Please check the docs
