### ISSUE TITLE
bug: typo / missing char in Readme

### ISSUE THREAD

**Issue by xo68** [folke/trouble.nvim#371]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9

### Operating system/version

MacOs

### Describe the bug

Hi,

In the Readme, i just did copy paste all the default configuration sample code to play with some parameters and I spotted a missing comma.
before: _`next = "j" -- next item`_
after: _`next = "j", -- next item`_

Greetings,
Xavier.

### Steps To Reproduce

n/a

### Expected Behavior

n/a

### Repro

```Lua
n/a
```

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
