### ISSUE TITLE
bug: is lsp-colors still needed?

### ISSUE THREAD

**Issue by 10b14224cc** [folke/trouble.nvim#375]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Documentation issue

### Operating system/version

Documentation issue

### Describe the bug

README says to install lsp-colors to automatically create the missing highlight group.

But the [lsp-colors](https://github.com/folke/lsp-colors.nvim) repo says the project is archived and should be no longer needed.

Is lsp-colors still needed?

### Steps To Reproduce

Documentation issue

### Expected Behavior

Documentation issue

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
