### ISSUE TITLE
bug: Neovim crashes when you close all other windows

### ISSUE THREAD

**Issue by wojciech-kulik** [folke/trouble.nvim#378]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.5

### Operating system/version

macOS 14.2.1

### Describe the bug

Neovim crashes when you close the only other window

### Steps To Reproduce

1. Have just one window
2. Open Trouble
3. Call `:close` in the not-Trouble window

### Expected Behavior

The window is closed, and Trouble is expanded.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
