### ISSUE TITLE
bug: `:Trouble workspace_diagnostics` is only showing diagnostics for open buffers with tsserver

### ISSUE THREAD

**Issue by dan-cooke** [folke/trouble.nvim#379]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

Arch Linux 

### Describe the bug

Previous issue
https://github.com/folke/trouble.nvim/issues/26

I'm working on a Typescript project when I notice the issue

It doesn't seem to be an issue with rust-analyzer so its maybe a TSServer issue

### Steps To Reproduce

Ensure tsserver is installed and trouble and your lsp are configured

1. `mkdir bug && cd bug && nvim file1.ts`
```
const test = 1

test  = 2
```
2. Close neovim
3. `neovim another.ts`
4. Open trouble

### Expected Behavior

It should should show 

   file1.ts  1 
 │     Cannot assign to 'test' because it is a constant. typescript (2588) [3, 1]

**Comment by folke** [comment]
That's a limitation of tsserver

**Comment by rbhanot4739** [comment]
@folke Apparently I am having same issue with Pyright(Basedpyright as well), where `Trouble diagnostics` only shows the diagnostics for the open buffers and not the entire workspace. Btw I am using the standard default LazyVim config for Trouble.

**Comment by folke** [comment]
That's just how pyright works and how they implement the LSP protocol

**Comment by rbhanot4739** [comment]
Oh I think I found the solution, for `Pyright` or `Basedpyright`, we need to set the lsp setting `diagnosticMode : "workspace`.

**Comment by MannyFay** [comment]
Hey, ...and after all of you no it better than me, can me somebody explain in a little more detail how to use Trouble for displaying all diagnostics in my project?
I'd like it to use for my Next.js/React/TS environments. If 'that's just how ... works' is ok for me, but how I have to configure eslint, tsserver, ts_ls for it to make it work, cause Trouble is a nice tool for that purpose.

**Comment by MannyFay** [comment]
Got it 😁 

I've installed the plugin [artemave/workspace-diagnostics](https://github.com/artemave/workspace-diagnostics.nvim).  
By now, this is my configuration in `lspconfig.lua`:  
```lua
    mason_lspconfig.setup_handlers({

      ----- Default handler for installed servers:
      function(server_name)
        lspconfig[server_name].setup({
          capabilities = capabilities,
          on_attach = function(client, bufnr)                                               -- Attach the following to every buffer.
            require("workspace-diagnostics").populate_workspace_diagnostics(client, bufnr)  -- Populate Workspace-Diagnostics plugin information.
          end,
        })
      end,
```
My whole [lspconfig.lua file](https://github.com/MannyFay/nvim/blob/smooth-nvim/lua/plugins/active/lsp/lspconfig.lua). Thanks to [Josean Martinez](https://github.com/josean-dev) too (...by the way.. ;-P).  

...and here is my `workspace-diagnostics.lua` configuration by now:  
```lua
-------------------------------------------------------------------------------
-- Workspace Diagnostics Plugin
-- https://github.com/artemave/workspace-diagnostics.nvim
-- Populates project-wide lsp diagnostics, regardless of what files are opened.
-------------------------------------------------------------------------------

return {
  "artemave/workspace-diagnostics.nvim",
  event        = { "BufReadPre", "BufNewFile" },
  dependencies = {
    "neovim/nvim-lspconfig",
    "folke/trouble.nvim",
  },
  config = function()
    require("workspace-diagnostics").setup({
      workspace_files = function()                -- Customize this function to return project files.
        return vim.fn.systemlist("git ls-files")  -- Example to get files from Git.
      end,
      -- Add any other configuration options as needed.
    })

    ---------------------------------------------------------------------------
    --- Key Mappings

    vim.api.nvim_set_keymap('n', '<space>x', '', {
      noremap = true,
      callback = function()
        for _, client in ipairs(vim.lsp.get_clients()) do
          require("workspace-diagnostics").populate_workspace_diagnostics(client, 0)
        end
      end,
      desc = "Populate workspace diagnostics"
    })
  end,
}
```

For me, now it works in my projects with Folke's awesome Trouble plugin - made my day :)

**Comment by disrupted** [comment]
I created a new issue for this: #682
currently Trouble only supports push-based workspace diagnostics and hasn't added support for pull-based LSP workspace diagnostics which are now natively supported in Neovim
