### ISSUE TITLE
bug: list not properly formatted with the theme

### ISSUE THREAD

**Issue by steakhutzeee** [folke/trouble.nvim#381]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.9.5

### Operating system/version

WSL 2

### Describe the bug

Hi,

i'm experiencing the same as in https://github.com/folke/trouble.nvim/issues/345

Looks like the list is not properly formatted with theme. How can we fix this?

Screenshot attached.

### Steps To Reproduce

Use any other theme rather than tokyonight.

### Expected Behavior

The list to be displayed correctly.

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by winter-again** [comment]
I think you have to add the missing [highlight groups](https://github.com/folke/tokyonight.nvim/blob/610179f7f12db3d08540b6cc61434db2eaecbcff/lua/tokyonight/theme.lua#L397) to whatever colorscheme you're using. Tokyonight already has them.
