### ISSUE TITLE
feature: Interaction with oil.nvim buffers

### ISSUE THREAD

**Issue by Rubenduburck** [folke/trouble.nvim#397]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

When opening any trouble panel with results, if I leave the buffer to go to an oil buffer (file explorer) and then go into the still loaded trouble panel and attempt to load a preview for any of the items, Trouble fails with error `trouble/view/preview.lua:91: attempt to index field 'preview' (a nil value)`. These errors continue every 100ms as long as Trouble is running.

### Describe the solution you'd like

Would like the Trouble panel to load the preview as it does normally

### Describe alternatives you've considered

The only way around this is to make sure not to enter a Trouble panel whenever in oil.nvim.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been fixed/implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Comment by Rubenduburck** [comment]
> Development on the main branch is EOL.
> 
> Trouble has been rewritten and will be merged in main soon.
> 
> This issue/feature either no longer exists or has been fixed/implemented on dev.
> 
> For more info, see https://github.com/folke/trouble.nvim/tree/dev

Forgot to mention, I'm on dev.
Did not have this problem before dev.

**Comment by folke** [comment]
`trouble/view/preview.lua` does not exist on dev.
So you're not on dev or at least didnt update with lazy or your package manager

**Comment by Rubenduburck** [comment]
> `trouble/view/preview.lua` does not exist on dev. So you're not on dev or at least didnt update with lazy or your package manager

[](https://github.com/folke/trouble.nvim/blob/dev/lua/trouble/view/preview.lua)

Maybe I'm missing something

**Comment by folke** [comment]
Yes, sorry, didnt check that good enough :)

You probably only have an oil window and a troubke window? No windows with regular buffers?

That's what's causing the error.

I'll have to see how to properly deal with this.

I'm leaving on a vacation in half an hour though, so will be for in a week or two.

**Comment by Rubenduburck** [comment]
> Yes, sorry, didnt check that good enough :)
> 
> You probably only have an oil window and a troubke window? No windows with regular buffers?
> 
> That's what's causing the error.
> 
> I'll have to see how to properly deal with this.
> 
> I'm leaving on a vacation in half an hour though, so will be for in a week or two.

Yeah that's exactly right, trouble window + oil window.

Enjoy!

**Comment by maxbol** [comment]
+1, would love to see this fixed :)

**Comment by folke** [comment]
Should be fixed now. Let me know if it still gives issues.
