### ISSUE TITLE
bug v3: diagnostic icon can not display

### ISSUE THREAD

**Issue by a1401358759** [folke/trouble.nvim#407]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2755+ge1ff2c51c

### Operating system/version

archlinux 6.8.1-arch1-1

### Describe the bug

diagnostic icon can not display

![image](https://github.com/folke/trouble.nvim/assets/15830146/2ca3e895-6460-4a79-85f5-74b17cf67f74)

### Steps To Reproduce

no

### Expected Behavior

no

### Repro

this is my config

```lua
return {
  "folke/trouble.nvim",
  lazy = true,
  branch = "dev", -- IMPORTANT!
  cmd = { "Trouble", "TroubleToggle", "TroubleRefresh" },
  keys = {
    {
      "<leader>xx",
      "<cmd>Trouble diagnostics toggle<cr>",
      desc = "Diagnostics (Trouble)",
    },
    {
      "<leader>xX",
      "<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
      desc = "Buffer Diagnostics (Trouble)",
    },
    {
      "<leader>cs",
      "<cmd>Trouble symbols toggle focus=false<cr>",
      desc = "Symbols (Trouble)",
    },
    {
      "<leader>cS",
      "<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
      desc = "LSP references/definitions/... (Trouble)",
    },
    {
      "<leader>xL",
      "<cmd>Trouble loclist toggle<cr>",
      desc = "Location List (Trouble)",
    },
    {
      "<leader>xQ",
      "<cmd>Trouble qflist toggle<cr>",
      desc = "Quickfix List (Trouble)",
    },
  },
}
```

**Comment by tummetott** [comment]
Trouble v3 is only installed if you pick the "dev" branch

**Comment by a1401358759** [comment]
@tummetott 
![image](https://github.com/folke/trouble.nvim/assets/15830146/c56e5567-b681-4f73-bc2e-6a56deb3cb8a)

this is my config

**Comment by tummetott** [comment]
Ah ok sorry. The purpose of the `repro` section in the issue is to give a minimal config so people can reproduce your problem. Maybe you can update that and provide your config there?

**Comment by a1401358759** [comment]
Ah sorry. it's my fault!
