### ISSUE TITLE
feature: Highlight group for Lualine components

### ISSUE THREAD

**Issue by Isrothy** [folke/trouble.nvim#411]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I found the background color of the lualine component is inconsistant with my lualine config.

<img width="1431" alt="image" src="https://github.com/folke/trouble.nvim/assets/61075605/ef143f7f-49ae-405b-bf39-3cc93360a925">

### Describe the solution you'd like

Just like what [aerial](https://github.com/stevearc/aerial.nvim) does

<img width="1433" alt="image" src="https://github.com/folke/trouble.nvim/assets/61075605/a02ff606-a22d-4a1e-8261-4ac29d0a3492">

### Describe alternatives you've considered

no

**Comment by folke** [comment]
This was harder than it should be, but was able to fix it.
Check the readme about the lualine example and especially the `hl_group` option.
