### ISSUE TITLE
bug: Not displaying text / can't see items in Trouble

### ISSUE THREAD

**Issue by aindriu80** [folke/trouble.nvim#412]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev

### Operating system/version

POP_OS! 22.04 (Ubuntu based)

### Describe the bug

![2024-04-04_14-52](https://github.com/folke/trouble.nvim/assets/8885837/6c0b6832-4b57-48f3-8dc9-e84ac51d7968)

When I type `:Trouble` I see the screen in the attached image.  I can't see error messages - only this coloured screen

### Steps To Reproduce

1. Load up LazyVim
2. Type :Trouble
3. Notice the light coloured background instead of text with errors

### Expected Behavior

I expect to see the errors.

here is my trouble.lua in /plugins of lua

```
return {
  "folke/trouble.nvim",
  dependencies = { "nvim-tree/nvim-web-devicons" },
  opts = {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
    use_diagnostic_signs = true,
  },
}



```

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by aindriu80** [comment]
I've been trying it since (also the beta version).... it seems to work when in  a file with errors.

![2024-04-04_16-02](https://github.com/folke/trouble.nvim/assets/8885837/5e25ee49-2e64-43ad-8ffd-a8300aad83f7)

However the text is still covered

**Comment by folke** [comment]
That's just your colorscheme. Add proper highlught groups, or use a proper colorscheme like tokyonight, catppuccin, ...
