### ISSUE TITLE
attempt to call method 'match' (a nil value)

### ISSUE THREAD

**Issue by ReubenM** [folke/trouble.nvim#42]
Not certain what changed to make this start happening.

```E5108: Error executing lua trouble.nvim/lua/trouble/init.lua:32: attempt to call method 'match' (a nil value)```

**Comment by folke** [comment]
When do you get that?

**Comment by ReubenM** [comment]
when calling LspTroubleWorkspaceToggle.

Is this depreciated?

**Comment by sbromberger** [comment]
I get this with `auto_open = true` and a rust file with an error.

**Comment by folke** [comment]
This should be fixed now. Was due to a recent change to handle a custom `cwd`. Thank you for reporting!
