### ISSUE TITLE
feature: folding actions working globally across the fold

### ISSUE THREAD

**Issue by simonmandlik** [folke/trouble.nvim#420]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Actions like `"fold_open"` and `"fold_close"` do not work unless the cursor is positioned on top line of the fold (e.g. a filename or a directory). In order to close this fold, I have to jump to this top line and close the fold.

### Describe the solution you'd like

Actions like `"fold_open"` and `"fold_close"` working everywhere in the fold (like in vanilla neovim).

### Describe alternatives you've considered

It is possible to use global `"fold_more"` or `"fold_reduce"`, which work everywhere, however, they expand / collapse all folds.

**Comment by folke** [comment]
This has been fixed in v3

**Comment by simonmandlik** [comment]
@folke I have just tested this on `main`:

The following work everywhere (both inside the fold and in the top fold line):
- zm = "fold_more"
- zM = "fold_close_all"
- zr = "fold_reduce"
- zR = "fold_open_all"

The following work only when the cursor is positioned on the top fold line:
- zo = "fold_open"
- zO = "fold_open_recursive"
- zc = "fold_close"
- zC = "fold_close_recursive"
- za = "fold_toggle"
- zA = "fold_toggle_recursive"

**Comment by folke** [comment]
I think I was able to fix this. Would be great if you can confirm!

**Comment by simonmandlik** [comment]
Amazing! Thank you :)
