### ISSUE TITLE
feature: disable icons

### ISSUE THREAD

**Issue by chrisands** [folke/trouble.nvim#421]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Ability to disable icons since v2 allowed to do it

### Describe the solution you'd like

For example set in config empty dictionary
```lua
icons = {}
```

### Describe alternatives you've considered

-

### Additional context

v2 allows to disable icons using `icons = false`

**Comment by folke** [comment]
icons will only be enabled when you have the nvim-web-devicons plugin installed.

If you want to disable them even with the plugin installed, do something like:

```lua
require('trouble.format').formatters.file_icon = function() return "" end
```
