### ISSUE TITLE
feature: Add option to fix input under cursor

### ISSUE THREAD

**Issue by simonmandlik** [folke/trouble.nvim#427]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Any Trouble window that uses the symbol under the cursor (like `lsp_references`, `lsp_definitions`, etc...) switches to different set of results when the cursor moves to a different symbol. This is useful when I want to inspect references of multiple symbols, but not when I want to use Trouble as a qf replacement. If I want to make some nontrivial change, the symbol under the cursor will inevitably change and I will loose all results from the Trouble window.

### Describe the solution you'd like

Add an option to take the current symbol under the cursor only when invoking Trouble and not later (unless Trouble is re-invoked in a different location).

### Describe alternatives you've considered

It is possible to first export trouble results to e.g. Telescope or qf and jump using that, but it seems as a step that could be easily avoided

**Comment by folke** [comment]
You can set `auto_refresh = false`, or when in a trouble list, just press `R` to toggle `auto_refresh`
