### ISSUE TITLE
bug v3: popup error msg after create new buffer and set filetype to lua

### ISSUE THREAD

**Issue by Urie96** [folke/trouble.nvim#434]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-3004+gb13e63db1-Homebrew

### Operating system/version

macos 13.0

### Describe the bug

Error executing vim.schedule lua callback: ...vim/HEAD-b13e63d/share/nvim/runtime/lua/vim/lsp/util.lua:294: bad argument #1 to 'gmatch' (string expected, got nil)
stack traceback:
	[C]: in function 'gmatch'
	...vim/HEAD-b13e63d/share/nvim/runtime/lua/vim/lsp/util.lua:294: in function 'get_lines'
	...vim/HEAD-b13e63d/share/nvim/runtime/lua/vim/lsp/util.lua:322: in function 'get_line'
	...vim/HEAD-b13e63d/share/nvim/runtime/lua/vim/lsp/util.lua:335: in function 'get_col'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:212: in function 'location'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:194: in function 'location_to_item'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:149: in function 'add'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:165: in function 'cb'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:100: in function 'handler'
	...m/HEAD-b13e63d/share/nvim/runtime/lua/vim/lsp/client.lua:693: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>

### Steps To Reproduce

1. enable trouble v3 through Lazyvim { import = "lazyvim.plugins.extras.editor.trouble-v3" }
2. cd to an empty dir
3. nvim a.lua
4. run `:enew`
5. type `a=1`
6. run `:setf lua`
7. error msg  show, and repeatly popup error after moving cursor

### Expected Behavior

no error popup

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
Should be fixed now
