### ISSUE TITLE
feature: Can we use real buffer for preview?

### ISSUE THREAD

**Issue by xzbdmw** [folke/trouble.nvim#435]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I v2 the auto_preview actually opens the buffer and set cursor to location, while in v3 there is only syntax highlight in preview, which makes some plugin that reacts to bufenter no longer works, for example, gitsigns don't work on preview, and builtin diagnose right align to cursorline is not showing too. I have to actually type enter.

For example, it would be much better If I can edit the text directly in [split preview](https://github.com/folke/trouble.nvim/blob/dev/docs/examples.md#preview-in-a-split-to-the-right-of-the-trouble-list) without having to enter main window, by that way I can see two buffer at the same time and my eyes don't need to jump from right preview to main window.

### Describe the solution you'd like

Actually open the buffer and set cursor

### Describe alternatives you've considered

Hmm

**Comment by yavorski** [comment]
Hmm, for some reason I don't even have syntax highlight either. Previews are just white text?

**Comment by xzbdmw** [comment]
@yavorski highlights comes from [treesitter.start](https://github.com/folke/trouble.nvim/blob/e2185bf6e63ef9bd75f1819f43846e2b0f10953b/lua/trouble/view/preview.lua#L54)

**Comment by Mado13** [comment]
well it will also be nice to be able to edit inside of preview if its a real buffer

**Comment by yavorski** [comment]
> @yavorski highlights comes from [treesitter.start](https://github.com/folke/trouble.nvim/blob/e2185bf6e63ef9bd75f1819f43846e2b0f10953b/lua/trouble/view/preview.lua#L54), you can remove that pcall to see if there are errors

@xzbdmw No difference, there is no highlight, screenshot attached. Telescope references are working fine though.

![trouble-white-text-preview](https://github.com/folke/trouble.nvim/assets/3436517/698e9941-71fb-4ec2-baf4-e32652391104)

**Comment by xzbdmw** [comment]
> > @yavorski highlights comes from [treesitter.start](https://github.com/folke/trouble.nvim/blob/e2185bf6e63ef9bd75f1819f43846e2b0f10953b/lua/trouble/view/preview.lua#L54), you can remove that pcall to see if there are errors
> 
> @xzbdmw No difference, there is no highlight, screenshot attached. Trouble v2 and Telescope references are working fine though.
> 
> ![trouble-white-text-preview](https://private-user-images.githubusercontent.com/3436517/334570716-698e9941-71fb-4ec2-baf4-e32652391104.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY5MzE2ODksIm5iZiI6MTcxNjkzMTM4OSwicGF0aCI6Ii8zNDM2NTE3LzMzNDU3MDcxNi02OThlOTk0MS03MWZiLTRlYzItYmFmNC1lMzI2NTIzOTExMDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjhUMjEyMzA5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjI5MWVkMGQ1MTE3YTk0OTVkN2YyNTVhMzBiYjI3ZDRlNmEwMDhkZGI2NDQ4MTYzN2MxYmM4ZWQwNjg5NmUzNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Q5nMIrN6MrE8uBRtrkHrnX7C46NJAfqj1gNAkQCwgJQ)

Then it maybe a bug, you can file a issue

**Comment by folke** [comment]
@yavorski the issue you had was specifically for unloaded typescript files, and was caused due to a quirk in how the ftdetect for typescript works in Neovim.

I was able to fix it.

**Comment by folke** [comment]
You can now set `opts.preview.scratch = false` to always load the preview in a real buffer
