### ISSUE TITLE
bug: error when quitting vim with trouble window open

### ISSUE THREAD

**Issue by santhosh-tekuri** [folke/trouble.nvim#439]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.11

### Operating system/version

MacOS Sonoma

### Describe the bug

quitting Nvim with trouble window open gives error

### Steps To Reproduce

1. open trouble diagnostics window
2. make sure some buffer has focus. i.e trouble window is not in focus
3. type `:q` and following error appears

```
Error detected while processing BufEnter Autocommands for "<buffer=7>":
E5108: Error executing lua ....local/share/nvim/lazy/trouble.nvim/lua/trouble/view.lua:357: Vim:E444: Cannot close last window
stack traceback:
        [C]: in function 'nvim_win_close'
        ....local/share/nvim/lazy/trouble.nvim/lua/trouble/view.lua:357: in function 'on_enter'
        ....local/share/nvim/lazy/trouble.nvim/lua/trouble/init.lua:215: in function 'action'
        [string ":lua"]:1: in main chunk
```

### Expected Behavior

Nvim should quit normally

**Comment by folke** [comment]
The main branch is no longer maintained. All new development happens on the dev branch which will become main at some point.
