### ISSUE TITLE
[Feature] some external function

### ISSUE THREAD

**Issue by windwp** [folke/trouble.nvim#44]
How do I move to the next item on trouble but my current buffer is not in trouble? If i use quick fix i can do that.
I want display the total error warning and hint in my custom statusline for filetype. Can you expose some function to get that data.
Thank you.

**Comment by folke** [comment]
You want to go to the location of the next/previous trouble item?

You can do this by first advancing the current item and then triggering a jump, like this:

```lua
:lua require("trouble").action("next"); require("trouble").action("jump")
```


The best way to get diagnostic counts is to use the built-in `vim.lsp.diagnostic.get_count` API, or use `vim.lsp.diagnostic.get_all` and count the things you need.

**Comment by windwp** [comment]
```:lua require("trouble").action("next"); require("trouble").action("jump")```
It work but if It jump to a fold . It will close fold too.
I only want to jump to a next todo :)

How about to display the todo total item.
![image](https://user-images.githubusercontent.com/7578110/120758836-8715e200-c53c-11eb-85b0-21b8aa5ab9bc.png)

**Comment by folke** [comment]
I just added this. Please refer to the [documentation](https://github.com/folke/trouble.nvim#api) to use it
