### ISSUE TITLE
feature: add support for markdown outline

### ISSUE THREAD

**Issue by imroc** [folke/trouble.nvim#440]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I used symbols-outline.nvim as `<leader>cs`, it support markdown, but not supported any more when switch to trouble-v3, which only support LSP Document Symbols.

### Describe the solution you'd like

no

### Describe alternatives you've considered

 symbols-outline.nvim

**Comment by folke** [comment]
I initially planned to implement this in trouble as well, but then I noticed that you can just use the lsp server `marksman`.
Since that's an LSP server, document symbols also work.

See for example:

![image](https://github.com/folke/trouble.nvim/assets/292349/45fd1e11-f165-4ebe-bd85-def3c659c7d7)

**Comment by imroc** [comment]
Wow! that's nice, happy to see it's also in LazyVim's extras!
