### ISSUE TITLE
feature: qflist can also have treesitter syntax highlight

### ISSUE THREAD

**Issue by xzbdmw** [folke/trouble.nvim#441]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Currently qflist is plain text

### Describe the solution you'd like

Apply tressitter highlight to them same as telescope integration(this has syntax highlight on lines)

### Describe alternatives you've considered

No

**Comment by folke** [comment]
Added!
