### ISSUE TITLE
feature: disable folder etc.. icons

### ISSUE THREAD

**Issue by Arisa-Snowbell** [folke/trouble.nvim#442]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

![image](https://github.com/folke/trouble.nvim/assets/22961592/72e3c69c-8e0d-4c65-92c1-7eb88cce6806)
don't want these icons

### Describe the solution you'd like

option to disable all of the icons with one variable

### Describe alternatives you've considered

?

**Comment by folke** [comment]
Check the diagnostics source src code.

You will want to change the group for `{ "directory" }` to something like `{ "directory", format  = "{dirname}" }`.

You can just add all of that to your trouble config.

Same for the others.
