### ISSUE TITLE
bug v3: Remove branch dev in readme file

### ISSUE THREAD

**Issue by minhtien3297** [folke/trouble.nvim#447]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.1

### Operating system/version

MacOS 14.5

### Describe the bug

In the readme file in install guide, the dev branch still exists in main branch's readme file

### Steps To Reproduce

![image](https://github.com/folke/trouble.nvim/assets/66081361/8a83fb88-0121-4cf3-9cfc-7e8a087abdae)

### Expected Behavior

Remove branch dev because it causes error when updating

**Comment by folke** [comment]
Good catch. Fixed!
