### ISSUE TITLE
Sign rendering code seems to have an inverted condition

### ISSUE THREAD

**Issue by therealprof** [folke/trouble.nvim#448]
Hi,

I was briefly looking into why trouble fails to render the correctly configured sign icons and instead uses the first letter of the severity instead.

It occured to me that this condition is wrong

https://github.com/folke/trouble.nvim/blob/91cab162e69ee46296c264438e27b61051b8c880/lua/trouble/format.lua#L66

since the else branch uses `vim.fn.sign_getdefined()` which **does** exist in nvim 0.10. Indeed flipping the condition makes trouble render the icon instead of the letter just fine.

However I'm not sure there's no more correct way to do version checks since that first branch is probably supposed to be used for all older versions instead of all versions not being 0.10 and I'm not sure how those nvim feature flags work.

**Comment by folke** [comment]
https://github.com/folke/trouble.nvim/issues/449

**Comment by therealprof** [comment]
It seems rather odd to declare a non-deprecated API, literally everyone uses, obsolete and break existing configs for no apparent reason. `gitsigns`, `lualine`, `trouble v2` and other plugins work just fine with `sign_define`, only `trouble v3` looks rather dated now.

With your pointer and the help of https://neovim.io/doc/user/diagnostic.html#diagnostic-signs I managed to adjust the config to support old and new style but since I couldn't find any tutorials or example configs using the "recommded" API, I think it will take a while until the world catches up...

**Comment by folke** [comment]
Allright, I'll see if I can just also use the old values if needed.

**Comment by folke** [comment]
I think I fixed it

**Comment by therealprof** [comment]
Doesn't look like it, with the latest `main` and after backing out the new configuration:

<img width="916" alt="Screenshot 2024-05-31 at 19 29 37" src="https://github.com/folke/trouble.nvim/assets/3321888/31de0a50-db8e-4b10-8cd0-c70495285764">

**Comment by folke** [comment]
Can you check again?

**Comment by therealprof** [comment]
Looking good now. 👍🏻
