### ISSUE TITLE
bug: slowdown / freeze with large test output

### ISSUE THREAD

**Issue by folke** [folke/trouble.nvim#452]
### Discussed in https://github.com/folke/trouble.nvim/discussions/293

<div type='discussions-op-text'>

<sup>Originally posted by **dvic** June  5, 2023</sup>
I'm using the neotest plugin together with the elixir adapter and I'm facing some performance issues when a failing test outputs a large of amount of text (the ui freezes and becomes unresponsive).

Any idea how I can figure out if the problem lies with `trouble.nvim` or with `neotest`/`neotest-elixir` ?</div>

**Comment by mycf** [comment]
locations_to_items read file together，maybe can use paging query，or no need location info（in big number）
