### ISSUE TITLE
bug: latest update throws error

### ISSUE THREAD

**Issue by shaz-at-vume** [folke/trouble.nvim#455]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.9.5

### Operating system/version

PopOs

### Describe the bug

The latest update throws the above error whenever I scroll through any of the files
![Screenshot from 2024-05-31 16-10-21](https://github.com/folke/trouble.nvim/assets/110542373/b9565efb-eda8-490b-ab96-d03d9764104f)

### Steps To Reproduce

1. Open NVIM
2. Open any file and try to scroll

### Expected Behavior

No error during scrolling

**Comment by folke** [comment]
Should be fixed now. Can you check if all is ok?

**Comment by shaz-at-vume** [comment]
> Should be fixed now. Can you check if all is ok?

Yassss, thanks :heart:
