### ISSUE TITLE
bug: not use current buffer lsp client

### ISSUE THREAD

**Issue by mycf** [folke/trouble.nvim#458]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.11.0-dev-4512+g4b0291633-Homebrew

### Operating system/version

macos

### Describe the bug

when i in a java file, I tigger Trouble lsp_references,I got
```
   Warn  22时59分39秒 notify.warn Trouble No results for **lsp_references**
```

<img width="1153" alt="image" src="https://github.com/folke/trouble.nvim/assets/36999825/97a43dc7-3ea2-41c6-b130-610050a08bfa">

### Steps To Reproduce

Triggers  Trouble lsp_references  at the arrow position
<img width="1374" alt="image" src="https://github.com/folke/trouble.nvim/assets/36999825/213f42af-4da4-47dc-923f-4ac8c8e2394d">

### Expected Behavior

got java references

**Comment by folke** [comment]
Before I look into this, can you first make sure you're using the latest HEAD of trouble?
