### ISSUE TITLE
Errors recognized only after files are visited

### ISSUE THREAD

**Issue by vuki656** [folke/trouble.nvim#46]
Hey, thanks for the really cool plugin.

I noticed that when I open a project and do `lsp_workspace_diagnostics` search, the list will be empty even if there are errors in the project.

Only after I visit the files with errors in them, will they show up in trouble.

Is this a limitation of nvim's LSP or intended behavior?

**Comment by folke** [comment]
That's a limitation (or configuration) of your lsp server. Nothing we can do about that.
