### ISSUE TITLE
feature: allow drilling down in call hierarchies

### ISSUE THREAD

**Issue by folke** [folke/trouble.nvim#463]
Hi @folke, I tried it out, and it's not exactly what I expected from a call-hierarchy UI.

In such UI I expect the incoming calls entries to recursively have their parents in the tree as well. See: <https://github.com/marcomayer/calltree.nvim>.
This way you could easily see the "call stack" of a function you're inspecting, and quickly jump to any of its ancestors.

I thought that since `trouble` is a tree UI, it'd be a good fit for such use-case. What do you think?

_Originally posted by @shahamran in https://github.com/folke/trouble.nvim/issues/222#issuecomment-2143329683_

**Comment by shahamran** [comment]
Hi @folke, any chance to re-consider this?

**Comment by ravenxrz** [comment]
Is there any progress on this?

**Comment by jmacadie** [comment]
@ravenxrz I wrote about the general issues with this feature on [Neovim issue #26817](https://github.com/neovim/neovim/issues/26817#issuecomment-2580841794). You may find some of the links in my reply useful

**Comment by shahamran** [comment]
@jmacadie I'm not sure this is relevant here, can you clarify? The suggestion was to display one level, and then deeper levels upon user interaction, maintaining all results in the tree UI.

**Comment by jmacadie** [comment]
@shahamran apologies if I've misunderstood but I would say that that is _exactly_ what my plugin, which is a Telescope extension, does.

Obviously, what I have written is nothing to do with Trouble. However, some people who come across this issue may be looking for the functionality and not be set on using Trouble to address it. That being the case, I thought it would be helpful for those people to surface both what I had written and also other equivalent implementations that I have found. No worries if that's not useful to you.

If you don't like what I've written the other plugins that I came across that look to offer equivalent functionality are:
- [LspSaga](https://nvimdev.github.io/lspsaga/callhierarchy/)
- [calltree.nvim](https://github.com/marcomayer/calltree.nvim)
- [hierarchy-tree-go](https://github.com/crusj/hierarchy-tree-go.nvim)

I also thought my discussion of the considerations with addressing the problem space would be salient to this issue, should anyone want to build the functionality for Trouble in the future, as originally requested.

**Comment by ravenxrz** [comment]
> @ravenxrz I wrote about the general issues with this feature on [Neovim issue #26817](https://github.com/neovim/neovim/issues/26817#issuecomment-2580841794). You may find some of the links in my reply useful

Awesome, I will try this plugin later, and give you some feedback (if any).

**Comment by jmacadie** [comment]
Looks like I hitched my wagon to the wrong horse, with [snacks.picker](https://github.com/folke/snacks.nvim/blob/main/docs/picker.md) coming out overnight. I might look to port my plugin to that ecosystem & maybe even get it into the core snacks repo as a PR.

**Comment by anthraxx** [comment]
@jmacadie did you manage to create something experimental for snacks.picker? would love to offer some help getting it over the finish line.

**Comment by jmacadie** [comment]
@anthraxx I never got round to this. My day job is off-the-charts busy at the moment (and likely to stay that way for the next few months at least) so I don't really have the bandwidth to work on this right now. I would absolutely love to make progress on this if you can help out though.

The best way to take this forward would be to open [an issue on my repo](https://github.com/jmacadie/telescope-hierarchy.nvim/issues) and we can bikeshed out how it should work. I might be being naive but my intention was to write the core hierarchy engine without any reference to the UI, maybe in it's own repo, and then build the various UI implementations on top of that. This way we can support snacks, telescope, mini, fzf-lua etc. I already had this in mind when I built the add-in so you may find it not that much additional work to get up and running
