### ISSUE TITLE
bug: two winbar at the same time

### ISSUE THREAD

**Issue by b1nhack** [folke/trouble.nvim#464]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

macOS 14.5

### Describe the bug

Using the default preview options, when the preview content is in the current window, two winbars appear (I'm using lualine to customize the winbar).

### Steps To Reproduce

1. Display something in the winbar.
2. Preview some content contained in the current window using Trouble.

### Expected Behavior

Only one winbar.

**Comment by folke** [comment]
When I do `:set winbar=foobar`, then I don't see the duplicate winbars.
Can you give me the full steps to reproduce?

**Comment by folke** [comment]
I it fixed when you set `opts.preview.wo.winbar = ""`?
If so, I'll just add that to the defaults

**Comment by b1nhack** [comment]
> Is it fixed when you set `opts.preview.wo.winbar = ""`? If so, I'll just add that to the defaults

After following the above settings, the issue was resolved.
