### ISSUE TITLE
Send results to telescope

### ISSUE THREAD

**Issue by vuki656** [folke/trouble.nvim#47]
Hey,

I know there is a way to send telescope results to trouble.

But is there a way to send trouble results to telescope?

I find It easier to navigate telescope's picker when there are a lot of files in the project.

Thanks!

**Comment by folke** [comment]
Not yet, but I believe @runiq created something for that. Maybe he can share the code.

**Comment by vuki656** [comment]
> Not yet, but I believe @runiq created something for that. Maybe he can share the code.

Awesome, I hope he drops in to share it.

Do you maybe think this could be a part of the plugin, same as for `todo-comments` plugin you have `TodoTelescope`, here it would be `TroubleTelescope`?

**Comment by folke** [comment]
Yep, it would make sense to have a key binding to send the results to Telescope. I've asked @runiq on chat as well. So will see if I can add it once he responds.

**Comment by vuki656** [comment]
Hey I just found that it can be done [natively via telescope.](https://github.com/nvim-telescope/telescope.nvim#neovim-lsp-pickers)

Up to you if you would still like to implement it. 

Thanks for the help.

**Comment by runiq** [comment]
Hi, [working on it](https://github.com/runiq/telescope-trouble.nvim), but I'd rather make no promises. My ambitions eclipse my abilities, as usual. :o)

**Comment by folke** [comment]
@vuki656 if you need to lookup lsp stuff, then it's definitely better to use Telescope directly for sure.
