### ISSUE TITLE
No documentation for filters (except for examples)

### ISSUE THREAD

**Issue by tom-anders** [folke/trouble.nvim#473]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.0

### Operating system/version

Ubuntu 22

### Describe the bug

`README.md`/`trouble.nvim.txt` give some examples that use filters, but I'm missing explicit documentation on how to use them and which keys are available (e.g. `not`, `severity`, etc.)

I think there also should be an example on how to register and use a custom lua function as a filter.

### Steps To Reproduce

read the docs

### Expected Behavior

Docs give more detailed information about using and adding filters, and the available options.

**Comment by tom-anders** [comment]
Just wanted to say, Trouble v3 is an awesome update! But right now it's rather hard to configure things IMO, as you either need to look at the plugin's source code, or use the examples as "implicit documentation"

**Comment by folke** [comment]
Yeah, fair point.
Still need to document filters / sorters / groupings / sections / formatters

**Comment by b0ae989c** [comment]
I can come up with some documentations for filters. Something similar to https://github.com/folke/noice.nvim?tab=readme-ov-file#-filters

The available ones are documented in https://github.com/folke/trouble.nvim/blob/38915023a777b7f2422e503dc603f6a64b465bf5/lua/trouble/filter.lua#L30-L74

**Comment by folke** [comment]
@b0ae989c that would be great!
Know that with trouble, you can also filter on any item attribute.

I'd prefer having new docs under `docs/filter.md` and then add a link to it from the main readme.

Need to create other docs for formatting, sections, sorting, groups, etc
