### ISSUE TITLE
bug: unable to open multiple trouble splits within same keymap

### ISSUE THREAD

**Issue by rebelot** [folke/trouble.nvim#474]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

latest

### Operating system/version

macOS

### Describe the bug

I'd like to open symbols and lsp modes at once in vertical splits on the right of the editor (as in screenshot), but it seems that window id is not updated during the execution of the keymap

### Steps To Reproduce

```lua
vim.keymap.set("n", "<leader>xp", "<cmd>Trouble symbols toggle focus=true<CR><cmd>Trouble lsp toggle focus=false win.position=bottom win.relative=win win.size=.5<CR>")
```
however, lsp mode is always relative to the main window, and not to trouble symbols

### Expected Behavior

two vertically stacked splits on the right of the window from where the command was issued

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by folke** [comment]
That's working how it's supposed to work.
The `relative=win`, is the main window that opened trouble.
Use edgy.nvim to do what you want. You can check the LazyVim edgy config on how you can achieve this.
