### ISSUE TITLE
feature: Allow overriding filetype 

### ISSUE THREAD

**Issue by dmtrKovalenko** [folke/trouble.nvim#475]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I use another your plugin to make a nice sidebar with trouble windows (https://github.com/folke/edgy.nvim). But it is deduplicating windows by filetype so I would like to be able to set the custom file type per trouble window in the sidebar so they are always ordered correctly (now they might mix)

### Describe the solution you'd like

I'd like to be able to do `Trouble symbols focus=false filter.buf=0 results.win.bo.filetype=trouble_symbols` it looks like it is just hardcoded and there is no requirements to specifically set file type for trouble 

### Describe alternatives you've considered

I didn't found the way to workaround

**Comment by folke** [comment]
Trouble exposes window vars that you can use.
See how I use them in LazyVim: https://www.lazyvim.org/extras/ui/edgy
