### ISSUE TITLE
feature: make the other jump actions also fold on a node

### ISSUE THREAD

**Issue by NicoElbers** [folke/trouble.nvim#479]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

As far as I've found, it's currently not possible to combine folding a node and the "jump_close" functionality

### Describe the solution you'd like

Adding the below code after "jump_close", "jump_split" and "jump_vsplit" [here](https://github.com/folke/trouble.nvim/blob/915179759c9459b69faae90a38da6fc1ca6b90d7/lua/trouble/config/actions.lua#L91)

```lua
elseif ctx.node then
  self:fold(ctx.node)
end
```

### Describe alternatives you've considered

Alternatively allow users to create their own actions, this would be more flexible but it also may be a little overkill.

**Comment by folke** [comment]
If it's an action you want to execute from within the trouble window, then you can already do that.
See the config for the two filtering examples.

If not, you can just add new actions to `require('trouble.config.actions').actions`

Or you can do any of these:

```lua
-- pass an action function as key
require("trouble")[function()
  dd("foo")
end]({ mode = "diagnostics" })


-- open trouble and do an action
local view = require(trouble).open(opts)
if view then
  view:action(action, opts) -- action is a string or function like in the actions
end

-- just use the trouble api
local view = require(trouble).open(opts)
if view then
  view:wait(function()
    view.win:focus()
  end)
end
```

**Comment by NicoElbers** [comment]
Ah, I completely missed this. Thank you for the quick reply!

**Comment by folke** [comment]
Docs are missing on these things. Will write some soon :)
