### ISSUE TITLE
is there a way to prevent auto_open from stealing focus?

### ISSUE THREAD

**Issue by sbromberger** [folke/trouble.nvim#48]
First off, this is a great plugin. Thank you!

I have `auto_open = true` in my config. When I open up a file with errors, the trouble window opens... and steals focus from the main editing buffer.

Is there a way to disable that, or return focus to the editor window?

**Comment by HankelBao** [comment]
Same problem here. Wish there could be a solution to make the great plugin better.

**Comment by folke** [comment]
I'll change it. Shouldn't take focus in case of auto_open.

**Comment by sbromberger** [comment]
Thank you. This plugin is really great; I have already integrated it into my dev workflow and am dependent on it!

**Comment by folke** [comment]
That was actually a bug. It was already supposed to not steal the focus, but I broke it in a recent commit. Should work as expected now.
