### ISSUE TITLE
feature: Customize the source on the user side?

### ISSUE THREAD

**Issue by NGPONG** [folke/trouble.nvim#481]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

In my configuration, there are many scattered hacker code snippets that can implement custom sources, such as gitsigns, lsp_xxx, marks, etc. After thorough research, I found that it might be more appropriate and feasible to leave the task of custom sources to the plugins themselves. This not only centralizes the previously scattered snippets into a more suitable place, but also enhances maintainability and consistency. Although they may need to adhere to certain standards (perhaps?). Therefore, I would like to know if there are plans to open up the task of custom sources to the user side. If you think this is a good idea, I am willing to contribute the code (just need some help).

Regards!

### Describe the solution you'd like

see above

### Describe alternatives you've considered

see above

**Comment by folke** [comment]
Plugins can already create custom sources.
See todo-comments.nvim for an example

**Comment by NGPONG** [comment]
Thanks for your suggestion. please forgive my carelessness.
