### ISSUE TITLE
Trouble highlight links aren't updated since rename

### ISSUE THREAD

**Issue by akinsho** [folke/trouble.nvim#49]
Hi @folke,

I've been tweaking the colors for my trouble window, and according to the docs `TroubleText` is supposed to be a base for a few other text highlight groups. So I tried tweaking trouble text hoping it would affect the colours of the linked groups but it didn't. Inspecting those groups it seems that most of them link to the old highlight groups e.g. `TroubleText` -> `LspTroubleText`, I think somewhere along the linking highlight groups aren't being linked correctly?

Sorry that felt rambly so TLDR.
I've set `TroubleText` to `guifg=x guibg=x` but this doesn't update the highlights for `TroubleErrorText` for example. I tried sequencing things a bit differently but didn't see a difference.

**Comment by folke** [comment]
Should be fixed now! We only use the old groups if the theme defines them. Otherwise the new groups are used.
