### ISSUE TITLE
bug: Types not visible in trouble document symbols sidebar

### ISSUE THREAD

**Issue by zayihu** [folke/trouble.nvim#493]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0 Build type: Release LuaJIT 2.1.1716656478

### Operating system/version

ArchLinux, kernel 6.9.3

### Describe the bug

TypeScript types not visible in symbols panel, only interfaces.
![Screenshot_20240609_184900](https://github.com/folke/trouble.nvim/assets/167391787/14b240cd-4703-46ab-9ce5-85e05d1f11cc)

### Steps To Reproduce

0. load nvim config: https://github.com/zayihu/dotfiles/tree/main/nvim
1. Open project folder in nvim.
2. Open TypeScript types file.
3. Interfaces are visible as document symbols, types are not.

### Expected Behavior

Expecting TypeScript types to be visible as doc symbols too.

**Comment by folke** [comment]
If you use `:Trouble symbols`, then there's a filter added to only show the most relevant kinds.

See the config at https://github.com/folke/trouble.nvim?tab=readme-ov-file#%EF%B8%8F-configuration

I just checked and it seems that type defs have the kind `Variable`, which is weird tbh.

You can change the filter to inucde those or to include all.

You can also see all of them by using `:Trouble lsp_document_symbols` instead

**Comment by zayihu** [comment]
Thank you very much! Will try.
