### ISSUE TITLE
bug: compatibility with nvim-notify

### ISSUE THREAD

**Issue by kiyoon** [folke/trouble.nvim#495]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.4.1

### Describe the bug

In https://github.com/rcarriga/nvim-notify, it demonstrates that we can override `vim.notify` to theirs.

```lua
vim.notify = require("notify")
```

However, if you set it like this, the trouble notifications result in an error. It's due to a slightly different interface they have. I know it's not ideal to remap such a command but it is a widely-used plugin so I thought others would be wondering about it, thus reporting it :)

To address this, maybe trouble.nvim can check `require("notify")` and send the notification via the plugin, otherwise use `vim.notify`

### Steps To Reproduce

1. Install nvim-notify
2. call deprecated function like `require("trouble.providers.telescope").open_with_trouble()`

### Expected Behavior

No error should be thrown.

**Comment by folke** [comment]
If you do it like that then trouble can't intercept notifications, so yes, that's an error
