### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by santhosh-tekuri** [folke/trouble.nvim#502]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0

### Operating system/version

MacOS 14.0

### Describe the bug

opening `symbols` in float mode causes error

### Steps To Reproduce

try `Trouble symbols win.type=float` gives error
but trying `Trouble lap_document_symbols win.type=float` works as expected

### Expected Behavior

open symbols view in float window

**Comment by b0ae989c** [comment]
Which LSP are you working with? Also, could you provide a minimal repro config?
