### ISSUE TITLE
bug: weird formating of preview buffers on windows 11

### ISSUE THREAD

**Issue by chshrct** [folke/trouble.nvim#518]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Windows 11

### Describe the bug

![alacritty_I5E6aANBuO](https://github.com/folke/trouble.nvim/assets/2571218/0b96dfc6-19ef-4c7e-96d5-d4af719fe4be)
Hi, folke. After major update of Trouble on windows 11, I encountered issues with formatting preview buffers. Could you please advise on how to address this?

### Steps To Reproduce

-

### Expected Behavior

-

### Repro

```Lua
-- DO NOT change the paths and don't remove the colorscheme
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath, })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  "folke/tokyonight.nvim",
  "folke/trouble.nvim",
  -- add any other plugins here
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

vim.cmd.colorscheme("tokyonight")
-- add anything else here
```

**Comment by b0ae989c** [comment]
There is no preview buffer in your screenshot. What's the issue?

This should be https://github.com/folke/trouble.nvim/discussions

**Comment by chshrct** [comment]
![alacritty_yVrJu6Sk58](https://github.com/folke/trouble.nvim/assets/2571218/c2ebc8f1-a5e2-4837-b326-6a239c39bc3a)
Each line in the preview items from Trouble on Windows 11 ends with ^M. It seems like a CRLF issue.
