### ISSUE TITLE
Diagnostic Icons

### ISSUE THREAD

**Issue by kaykhancheckpoint** [folke/trouble.nvim#52]
Hi, how do i get the diagnostic icons in the gutter?

![image](https://user-images.githubusercontent.com/65535942/122529294-3bbc0300-d015-11eb-8515-b552ae7c9bec.png)

```
Plug 'kyazdani42/nvim-web-devicons'
Plug 'folke/trouble.nvim'
```

**Comment by folke** [comment]
Until my `lsp.config` PR lands, you can use the code below:

```lua
local signs = { Error = " ", Warning = " ", Hint = " ", Information = " " }
for type, icon in pairs(signs) do
  local hl = "LspDiagnosticsSign" .. type
  vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = "" })
end
```

**Comment by kaykhancheckpoint** [comment]
Added this after my plugins

```
lua << EOF
local signs = { Error = " ", Warning = " ", Hint = " ", Information = " " }
for type, icon in pairs(signs) do
  local hl = "LspDiagnosticsSign" .. type
  vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = "" })
end
EOF
```

It did not work

**Comment by kaykhancheckpoint** [comment]
@folke Can you tihnk of anything else i might be missing?

**Comment by folke** [comment]
@kaykhancheckpoint are you using LSP saga by any chance? If so don't put in the code I posted and configure the symbols through saga

**Comment by Johan-Palacios** [comment]
In my case this not works

**Comment by mattleong** [comment]
> At least for me, I had to add the snippet from [#52 (comment)](https://github.com/folke/trouble.nvim/issues/52#issuecomment-863885779) to my config, otherwise errors in the gutter would show with "E":
> 
> ```
> :echo sign_getdefined("LspDiagnosticsSignError")
> [{'name': 'LspDiagnosticsSignError', 'numhl': '', 'texthl': 'LspDiagnosticsSignError', 'linehl': '', 'text': 'E '}]
> ```
> 
> Is trouble.nvim supposed to set the signs automatically?

Wondering the same myself

**Comment by Johan-Palacios** [comment]
This works for me
`
vim.cmd [[
    sign define DiagnosticSignError text=  linehl= texthl=DiagnosticSignError numhl=
    sign define DiagnosticSignWarn text= linehl= texthl=DiagnosticSignWarn numhl=
    sign define DiagnosticSignInfo text=  linehl= texthl=DiagnosticSignInfo numhl=
    sign define DiagnosticSignHint text=💡  linehl= texthl=DiagnosticSignHint numhl=
]]
`
![image](https://user-images.githubusercontent.com/77251405/138577586-8f2c03c6-a78d-4e00-8a79-3e686cdf34db.png)

**Comment by rd3ka** [comment]
If you use the bleeding edge dev build of nvim,
`local hl = "DiagnosticSign" .. type`  works
For 0.51 build `local hl = "LspDiagnosticsSign" .. type` works

**Comment by omertuc** [comment]
> FWIW, I was having the same issue. Changing the sign from `LspDiagnosticsSign .. type` to `DiagnosticSign .. type` resolved the issue for me.

Thanks, that worked for me. I want to stress for people who try this:
It's `Diagnostic` not `Diagnostics`, it's *not* just the `Lsp` prefix that got removed

**Comment by Yutsuten** [comment]
`Warning` and `Information` has been renamed too.
Here's the difference between neovim 5.1 and 6.0:

```diff
 local signs = {
   Error = "E",
-  Warning = "W",
+  Warn = "W",
   Hint = "H",
-  Information = "I"
+  Info = "I",
 }
+
 for type, icon in pairs(signs) do
-  local hl = "LspDiagnosticsSign" .. type
+  local hl = "DiagnosticSign" .. type
   vim.fn.sign_define(hl, { text = icon, texthl = hl, numhl = "" })
 end
```

**Comment by PgBiel** [comment]
Updated for nvim 0.11 (`vim.fn.sign_define` seems to be deprecated now):

```lua
local signs = {
    Error = " ",
    Warn = " ",
    Hint = "󰌵 ",
    Info = " "
}

local signConf = {
  text = {},
  texthl = {},
  numhl = {},
}

for type, icon in pairs(signs) do
  local severityName = string.upper(type)
  local severity = vim.diagnostic.severity[severityName]
  local hl = "DiagnosticSign" .. type
  signConf.text[severity] = icon
  signConf.texthl[severity] = hl
  signConf.numhl[severity] = hl
end

vim.diagnostic.config({
  signs = signConf,
})
```
