### ISSUE TITLE
feature: Add code context to statusline or winbar 

### ISSUE THREAD

**Issue by 231tr0n** [folke/trouble.nvim#526]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Since trouble provides symbol outlines with v3, I taught it would be cool if trouble.nvim adds code context support which can be displayed in statusline or winbar.

### Describe the solution you'd like

Provide a customizable function which can be used to display current code context in winbar or statusline.

### Describe alternatives you've considered

[nvim-navic](https://github.com/SmiteshP/nvim-navic)

**Comment by folke** [comment]
you can easily implement this yourself using the same trouble output, but maybe a different format and setting it to winbar.

**Comment by kola-web** [comment]
That's how I did it, but I don't know why, it only shows up after executing the Trouble symbols 
```lua
    local symbols = trouble.statusline({
      mode = 'lsp_document_symbols',
      groups = {},
      title = false,
      filter = { range = true },
      format = '{kind_icon}{symbol.name:Normal}',
    })
    _G.my_symbols = symbols
    vim.o.winbar = '%f %{%v:lua.my_symbols.get()%}'
```
