### ISSUE TITLE
j and k move to next+2  / last+2 instead of next and last trouble

### ISSUE THREAD

**Issue by jordisantamaria** [folke/trouble.nvim#54]
When open trouble and press j, It don't go to next, go next of next, same with k goes to last of last instead of last.
https://gyazo.com/9cad82d5b9c45b2920182ae8e1bad2bd

With arrow keys It works as expected, going to next or last, but when using j or k, It doesn't.

**Comment by gukz** [comment]
Hit same issue!

**Comment by folke** [comment]
Have you updated? Should have been fixed somewhere last week

**Comment by jordisantamaria** [comment]
> Have you updated? Should have been fixed somewhere last week

It's fixed updating, thanks you.
