### ISSUE TITLE
feature:  Add formatting to error like typescript ones

### ISSUE THREAD

**Issue by hakkm** [folke/trouble.nvim#543]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

 ![image](https://github.com/user-attachments/assets/e216909c-7d85-4097-b998-7b4cfcb65861)

This image will describe the pain i'm in to understand the issue with my code.
The first line is not wrapped, is should go to the end of the error to understand it.
It has code so it need to be formatted 

### Describe the solution you'd like

 I've heard that the extension in vscode that implemented a solution for it (I forget the name) created an image of the code in svg i think and then render it in the window.

### Describe alternatives you've considered

 nothing

### Additional context

I would like it to be formatted properly like the completion documentation in vscode.

### Why I've chosen the formatting in trouble.nvim but not in a completion documentation
I didn't found a solution for that

**Comment by folke** [comment]
that's out of scope

**Comment by hakkm** [comment]
Do you have any sol for that, maybe that you're using.

**Comment by LukeWood** [comment]
@hakkm how did you get trouble.nvim to show a global list of typescript errors?  What language server did you use to do that?  I can't get it to work with ts_ls.
