### ISSUE TITLE
feature: Auto close on jump

### ISSUE THREAD

**Issue by Dooez** [folke/trouble.nvim#550]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

I'm always frustrated when i need to move cursor to close Trouble after jumping e.g. when browsing lsp references. 

### Describe the solution you'd like

An option to close trouble window after jump.

### Describe alternatives you've considered

Auto-close does not work for references, because the cursor is placed directly on the item, and the list is not empty.

**Comment by folke** [comment]
Check the docs. keys section

**Comment by taylorvance** [comment]
For future confused Lazy people, there is a difference between keys and opts.keys. The top level keys defines global keymaps, while opts.keys defines keymaps for the Trouble context. Here is a simple example.
```
{'folke/trouble.nvim',
    opts = {
        keys = {
          ['<cr>'] = 'jump_close',
        },
    },
    cmd = 'Trouble',
    keys = {
        {'<leader>xx', '<cmd>Trouble diagnostics open focus=true<cr>', desc='Diagnostics'},
    },
},
```
