### ISSUE TITLE
bug: Invalid buffer id error

### ISSUE THREAD

**Issue by NGPONG** [folke/trouble.nvim#556]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

lastest

### Operating system/version

linux

### Describe the bug

Hey there, I've been encountering an occasional error "invalid buffer id" during usage recently. The video below demonstrates this issue. To explain the video: since this is a completely random error, it can be effectively reproduced by repeatedly opening and closing the trouble list, which is why the video shows this extreme operation method.

Regards!

https://github.com/user-attachments/assets/0f6fb95c-f1c7-41f1-9029-27fb3e51a002

### Steps To Reproduce

see above

### Expected Behavior

see above

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/trouble.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by GitMurf** [comment]
Anyone else still having this issue? Anytime I am cycling through the results in Trouble and it "previews" the position in the main buffer, if I close that buffer then I get the wave of "Invalid buffer id: ..." errors and they keep going until I quit Neovim.

![image](https://github.com/user-attachments/assets/ccb0574e-a238-4cad-a035-e6b7699a764a)

Don't know if it matters, but I usually am using Trouble with Telescope results.
