### ISSUE TITLE
[Feature request] Add lsp_document_symbols

### ISSUE THREAD

**Issue by ourigen** [folke/trouble.nvim#56]
I like the UI of this plugin and would love to be able to integrate into my LSP environment. One thing I think would work well is adding the ability to show symbols so that one can keep the menu open on one side to reference assignments

**Comment by folke** [comment]
There's already plugins that do this like:
* https://github.com/simrat39/symbols-outline.nvim
* https://github.com/liuchengxu/vista.vim
* https://github.com/ray-x/navigator.lua
* https://github.com/stevearc/aerial.nvim

I'm not planning to add this to trouble :)
