### ISSUE TITLE
bug: vim/keymap lhs:expected string, got number 

### ISSUE THREAD

**Issue by kaykhan** [folke/trouble.nvim#566]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu 24.04

### Describe the bug

Running `Trouble diagnostic toggle` throws an error. 

![image](https://github.com/user-attachments/assets/1bc20552-42f7-4b77-8bec-135a2d58afff)

The keymaps (e.g leader xx) are not working either. Though my leader key works everywhere else.

### Steps To Reproduce

1. :Trouble diagnostic toggle

```
require("trouble").setup({
	keys = {
		{
			"<leader>xx",
			"<cmd>Trouble diagnostics toggle<cr>",
			desc = "Diagnostics (Trouble)",
		},
		{
			"<leader>xX",
			"<cmd>Trouble diagnostics toggle filter.buf=0<cr>",
			desc = "Buffer Diagnostics (Trouble)",
		},
		{
			"<leader>cs",
			"<cmd>Trouble symbols toggle focus=false<cr>",
			desc = "Symbols (Trouble)",
		},
		{
			"<leader>cl",
			"<cmd>Trouble lsp toggle focus=false win.position=right<cr>",
			desc = "LSP Definitions / references / ... (Trouble)",
		},
		{
			"<leader>xL",
			"<cmd>Trouble loclist toggle<cr>",
			desc = "Location List (Trouble)",
		},
		{
			"<leader>xQ",
			"<cmd>Trouble qflist toggle<cr>",
			desc = "Quickfix List (Trouble)",
		},
	},
})
```

### Expected Behavior

Expect diagnostic to be toggled on

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/trouble.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by max397574** [comment]
you are not supposed to put the `keys` thing into the trouble setup

look at the example in the readme

**Comment by kaykhan** [comment]
> you are not supposed to put the `keys` thing into the trouble setup
> 
> look at the example in the readme

Ah youre saying keys is a lazyvim specific thing.

**Comment by max397574** [comment]
> Ah youre saying keys is a lazyvim specific thing.

yes, see here for what you tried to do
https://github.com/folke/trouble.nvim?tab=readme-ov-file#lazynvim

there is also a `keys` field in trouble config but that's for keymappings to control the trouble window


why you got the error message you got:
the `keys` table of trouble is a table with key value pairs where the keys are used as `lhs` of mappings
just providing a list-like table lua implicitly sets the keys to indices which are numbers
you then get an error when these are tried to be used as lhs of mappings
