### ISSUE TITLE
bug: Incorrect Lualine Highlight

### ISSUE THREAD

**Issue by Isrothy** [folke/trouble.nvim#569]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

MacOS 14.6.1

### Describe the bug

The symbols and separators in Lualine have inconsistent highlights.

![QQ_1724208361558](https://github.com/user-attachments/assets/e1108414-1688-49d3-9886-61416e1d7274)

### Steps To Reproduce

1. Use a color scheme, for example, `"gbprod/nord.nvim"` 

```lua
return {
    "gbprod/nord.nvim",
    priority = 100,
    lazy = false,
    config = function()
        vim.cmd.colorscheme("nord")
    end,

}

```

2. Insert trouble statusline component into  into winbar.

Lualine configuration like this:
```lua
{
	"nvim-lualine/lualine.nvim",
	lazy = false,
	dependencies = {
		"nvim-tree/nvim-web-devicons",
	},

	config = function()
		local c = require("nord.colors").palette

		local trouble = require("trouble")
		local symbols = trouble.statusline({
			mode = "lsp_document_symbols",
			groups = {},
			title = false,
			filter = { range = true },
			format = "{kind_icon}{symbol.name:Normal}",
			-- The following line is needed to fix the background color
			-- Set it to the lualine section you want to use
			hl_group = "lualine_c_normal",
		})

		require("lualine").setup({
			winbar = {
				lualine_c = {
					{
						symbols.get,
						cond = symbols.has,
					},
				},
			},
		})
	end,
},

```

### Expected Behavior

The symbols and separators in Lualine have should have the same background.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
	spec = {
		{
			"folke/trouble.nvim",
		},
		{
			"neovim/nvim-lspconfig",
			lazy = false,
			config = function()
				require("lspconfig").lua_ls.setup({})
			end,
		},

		-- add any other plugins here
		{
			"gbprod/nord.nvim",
			priority = 100,
			lazy = false,
			config = function()
				vim.cmd.colorscheme("nord")
			end,
		},
		{
			"nvim-lualine/lualine.nvim",
			lazy = false,
			dependencies = {
				"nvim-tree/nvim-web-devicons",
			},

			config = function()
				local c = require("nord.colors").palette

				local trouble = require("trouble")
				local symbols = trouble.statusline({
					mode = "lsp_document_symbols",
					groups = {},
					title = false,
					filter = { range = true },
					format = "{kind_icon}{symbol.name:Normal}",
					-- The following line is needed to fix the background color
					-- Set it to the lualine section you want to use
					hl_group = "lualine_c_normal",
				})

				require("lualine").setup({
					winbar = {
						lualine_c = {
							{
								symbols.get,
								cond = symbols.has,
							},
						},
					},
				})
			end,
		},
	},
})
```

**Comment by qeisar** [comment]
Same issue with various color schemes: tokyonight, catppucin, kanagawa.

**Comment by alex35mil** [comment]
Try setting `StatusLine` highlight.

**Comment by Isrothy** [comment]
> Try setting `StatusLine` highlight.

Thank you, but it doesn't work. Nothing changes.

**Comment by alex35mil** [comment]
@Isrothy ah sorry, I missed you have it in a winbar. I fixed my issues with status bar and tab bar by adjusting `StatusLine` and `TabLine` highlights. There should be similar highlight for a winbar I believe.

**Comment by alex35mil** [comment]
AFAICT it’s `WinBar` and `WinBarNC`.

**Comment by Isrothy** [comment]
Thanks. It works!

**Comment by danielwe** [comment]
I'm also experiencing this issue. Since the underlying problem has not been solved, perhaps the issue should be reopened? It appears every time trouble and lualine are used together with almost any colormap that is not tokyonight or catppuccin. There are at least three open LazyVim discussions about this: https://github.com/LazyVim/LazyVim/discussions/3459, https://github.com/LazyVim/LazyVim/discussions/3583, https://github.com/LazyVim/LazyVim/discussions/4071.

Evidently, the fundamental problem is that `trouble.statusline(opts)` does not apply `opts.hl-group` to the entire status string, but leaves gaps that end up falling back to a different highlight group. That's as far as I could get; I'm afraid I don't have the Lua chops to work out a solution.

**Comment by EasonMo** [comment]
@danielwe In your configuration try to make it effective. It works in my config file as [options.lua#L61-L61](https://github.com/EasonMo/MozyVim/blob/master/lua/config/options.lua#L61-L61).

```lua
vim.api.nvim_set_hl(0, "StatusLine", { link = "lualine_c_normal" })
```

**Comment by niderhoff** [comment]
for me it's also broken in rose-pine:

<img width="496" alt="Image" src="https://github.com/user-attachments/assets/4607bce4-2b17-4907-b185-6c2c33c7a75b" />

my code

```lua
        local trouble_symbols = require('trouble').statusline({
            -- mode = 'symbols',
            mode = 'lsp_document_symbols',
            groups = {},
            title = false,
            filter = { range = true },
            format = '{kind_icon}{symbol.name:Normal}',
            hl_group = 'lualine_c_normal',
        })
        table.insert(opts.sections.lualine_c, {
            trouble_symbols and trouble_symbols.get,
            cond = function()
                return vim.b.trouble_lualine ~= false and vim.fn.winwidth(0) > 120 and
                    trouble_symbols.has()
            end,
        })
        vim.api.nvim_set_hl(0, "StatusLine", { link = "lualine_c_normal" })
```

**Comment by EasonMo** [comment]
@niderhoff `StatusLine` highlight group must be set after the color scheme loaded, or it will be overrided.

**Comment by niderhoff** [comment]
> [@niderhoff](https://github.com/niderhoff) `StatusLine` highlight group must be set after the color scheme loaded, or it will be overrided.

good catch!!
I can confirm that the builtin fix (using the hl_group setting on `require("trouble").statusline(...)` only works for tokynight and catppuccin, but in other color themes (such as rose-pine) it does not.

the fix using `vim.api.nvim_set_hl(0, "StatusLine", { link = "lualine_c_normal" })` does work however. But as you said, I need to make sure colorscheme is loaded *before* lualine.

**Comment by YanzhaoW** [comment]
`vim.api.nvim_set_hl(0, "StatusLine", { link = "lualine_c_normal" })` doesn't solve the problem completely because lualine uses different highlight groups for different modes. 

In the normal mode, it uses `lualine_c_normal`. But in the insert mode, it changes to `lualine_c_insert` and we have the same problem again.

**Comment by danielwe** [comment]
@YanzhaoW A general solution is provided in #616
