### ISSUE TITLE
bug: No Option To Wrap Long Lines

### ISSUE THREAD

**Issue by megaconfidence** [folke/trouble.nvim#576]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.1

### Operating system/version

MacOS

### Describe the bug

There's no option to wrap really long diagnostic lines, especially in the toggle pane
![image](https://github.com/user-attachments/assets/349a1a0b-d8af-43c4-9bf1-8b5fdb3fe9bb)

### Steps To Reproduce

.

### Expected Behavior

Ability to set line character count at which they wrap, or automatic line wrap based on buffer size

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/trouble.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by emarcotte-dh** [comment]
Did you check out https://github.com/folke/trouble.nvim/pull/326

**Comment by megaconfidence** [comment]
This fixes it. Thanks @emarcotte-dh!
