### ISSUE TITLE
feature: Config `cycle_results` and `skip_groups`

### ISSUE THREAD

**Issue by hjkatz** [folke/trouble.nvim#577]
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Hey there, thanks for the v3 rewrite! I appreciate your contributions to OSS.

While migrating my config I found a few settings that I'm not sure made it over, but I want to ask here in case I missed something.

I have the following configs:
```
cycle_results = true, -- cycle item list when reaching beginning or end
```

and in `next(opts)`:
```
require("trouble").next({
  skip_groups = true,
  jump = true,
})
```

Q1. Where/How can I enable `cycle_results` again? I would like the `prev`/`next` funcs to go around the list from bottom -> top, or top -> bottom, depending on the direction.

Q. Where is `skip_groups`? Is that still a thing?

### Describe the solution you'd like

N/A

### Describe alternatives you've considered

N/A

**Comment by hjkatz** [comment]
I still have this question.

**Comment by mikeduminy** [comment]
I've been looking for `skip_groups` too but with no success, would greatly appreciate any work towards that 🙏

**Comment by RyanCarrier** [comment]
I still have these questions :(

**Comment by michaelfortunato** [comment]
I have this question.
