### ISSUE TITLE
bug: attempt to index field icons (a boolean value)

### ISSUE THREAD

**Issue by ebiscaia** [folke/trouble.nvim#581]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.1

### Operating system/version

Fedora 40

### Describe the bug

Sometimes I receive the following message and can't go forward:
`...share/nvim/lazy/trouble.nvim/lua/trouble/view/render.lua:136: attempt to index field 'icons' (a boolean value)

### Steps To Reproduce

Run one the trouble commands

### Expected Behavior

Show the trouble window with relevant data

**Comment by coleYab** [comment]
I also encounter the same mistake today and I was able to fix it by changing my setup command for trouble from 
```
            require("trouble").setup({
                  icons=false
            })
```
to 

```
            require("trouble").setup({
                   icons={}
            })
```

And that fix my problem

**Comment by ebiscaia** [comment]
That worked for me too. However, it seems like the problem is somehow in the defaults because I had nothing set previously.

Thanks for the help

**Comment by folke** [comment]
Just check the docs. `icons=false` is simply not a valid option...

**Comment by ebiscaia** [comment]
I don't know if you were talking to me, but I would like to illustrate my situation:

- Here is a screenshot of the plugin with its defaults:
![04-10-24_18-15-37](https://github.com/user-attachments/assets/0f8eb639-04b1-4b57-b66e-e751b047bd52)


- And here is a screenshot of the plugin with @coleYab's suggestion:
![Uploading 04-10-24_18-16-28.png…]()
