### ISSUE TITLE
bug: Shipping very broken and unusable

### ISSUE THREAD

**Issue by cybergazer** [folke/trouble.nvim#588]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

Latest stable 0.10.2

### Operating system/version

Debian 12

### Describe the bug

This kind of works but has a massive amount of extreme bugs/issues that make it unusable. Using this on a stock installation of neovim and used Mason for the language servers. Tested this with both typescript and svelte same issues.

- When you open the selector from the bottom and close it, the cursor goes out of position and doesn't go back into the buffer
- Gives a permission denied issue when running the lsp and then closing it
- Can only get errors from the buffer regardless of which panel you're in. In the readme it says you can get project-wide errors but it doesn't work 
- The quickfix panel does nothing even if there are errors in the file or project

None of these issues existed before the rewrite.
Imo there really should be a stable branch. One that is put through extensive unit testing before release and is held back for stability. I really hope this is fixed because aside from this there's no other decent lsp system for neovim and without something like this I'm probably gonna go back to vscodium which has all this stuff working ootb.

### Steps To Reproduce

Following instructions in readme

### Expected Behavior

For it to work

### Repro

```lua
Pretty much just copy/paste what's in the readme and it'll happen on stock, latest stable branch of neovim.
```

**Comment by folke** [comment]
I can't reproduce any of this. Please open seperate issues for anything that is broken accoriding to you and add proper repros
