### ISSUE TITLE
bug: Trouble windows should set `winfixbuf`

### ISSUE THREAD

**Issue by dlyongemallo** [folke/trouble.nvim#593]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

Ubuntu 22.04

### Describe the bug

Trouble's special windows do not set [winfixbuf](https://www.reddit.com/r/neovim/comments/1bbuh3z/big_news_winfixbuf_has_merged_into_neovims_core/). In particular, when in the qflist window, using `:cnext` or `:cprev` results in a `Cursor position outside buffer` error (whereas neovim's own `copen`/`cfile` window handles this perfectly fine).

### Steps To Reproduce

1. `nvim -u repro.lua`
2. `:cfile cfile.txt` (attached [cfile.txt](https://github.com/user-attachments/files/17486740/cfile.txt))
3. `:copen`, switch to this window
4. `:cnext`, works perfectly fine
5. `:Trouble qflist toggle`, switch to the Trouble window
7. `:cnext`, results in error

### Expected Behavior

`:cnext` and `:cprev` should work as if in the native `copen` window.

Note: If `:set winfixbuf` is used inside the Trouble window, then `:cnext` and `:cprev` work as expected.

### Repro

```lua
-- use vim-plug
local vim = vim
local Plug = vim.fn['plug#']

vim.call('plug#begin')
Plug('folke/trouble.nvim')
vim.call('plug#end')
require("trouble").setup()
```

**Comment by jonsmithers** [comment]
I also encounter this issue when I mess with the windows while Trouble is open. Specifically if I close every window except the trouble window using `<c-w>o`, and then press `enter` to jump to the selected diagnostic.

**Comment by dlyongemallo** [comment]
If anyone else has the same problem, I worked around this by putting the following in my `~/.config/nvim/after/ftplugin/trouble.lua`:

```lua
vim.keymap.set('n', ']q', 'j', { buffer = 0, noremap = true, silent = true })
vim.keymap.set('n', '[q', 'k', { buffer = 0, noremap = true, silent = true })
```

**Comment by paul-hansen** [comment]
This is still a problem and shouldn't be closed imo.
Doing things with your quickfix list like `:cdo %s/match/replace/g` to search and replace spams so many notifications of `Cursor position outside buffer` that I have to close neovim or stop using notify.nvim.

## Workaround

What worked for me was putting this in my init.lua:
```lua
vim.api.nvim_create_autocmd({"BufWinEnter", "WinEnter"}, {
    pattern = "*",
    callback = function()
        if vim.bo.filetype == "trouble" then
            vim.wo.winfixbuf = true
        end
    end
})
```
Note that simply setting `vim.wo.winfixbuf = true` in `ftplugin/trouble.lua` didn't work as it seemed to be overridden after that ran.
