### ISSUE TITLE
bug: attempt to index field 'languagetree'|'source' (a nil value)

### ISSUE THREAD

**Issue by hotung1027** [folke/trouble.nvim#599]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.0

### Operating system/version

WSL Ubuntu-20.04

### Describe the bug

![image](https://github.com/user-attachments/assets/fe362025-758f-4c7b-9a52-697c563198ff)

### Steps To Reproduce

1. enter neovim, lua config files, (not confirmed for another language yet)
2. The Trouble screen try to show
3. index field errors pop up

### Expected Behavior

Expected should be worked as V2, and no error will pop up

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/trouble.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by hotung1027** [comment]
Maybe due to this line,
` local ok, parser = pcall(vim.treesitter.languagetree.new, buf, lang)`
(https://github.com/folke/trouble.nvim/blame/2f3b537f2207ce32f4459f9d56746ee013b5e01b/lua/trouble/view/treesitter.lua#L68)

After I fallback to tag v3.6.0, everything worked for me

**Comment by iceout** [comment]
I have the same issue.

**Comment by hotung1027** [comment]
You can try [snacks.nvim](https://github.com/folke/snacks.nvim), the jack of all trades plugin developed by Folke. It is highly performant and integrated with many features.

**Comment by MattsonCam** [comment]
I also have the same issue

**Comment by bendangelo** [comment]
Same issue here v0.9.5
