### ISSUE TITLE
bug: Duplicate references when using angularls and ts language server

### ISSUE THREAD

**Issue by m4kamran** [folke/trouble.nvim#601]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10

### Operating system/version

Linux / Ubuntu 24.04

### Describe the bug

When angularls and typescript are both setup. We can see duplicate references:

![image](https://github.com/user-attachments/assets/5b7eb456-69bc-4339-887b-5fa0cb722d8b)

### Steps To Reproduce

1. Install angular and a typescript language server.
2. Check for references in a ts file.
3. Angular and TS both

### Expected Behavior

Reference should only be shown once. Or maybe have an option to select one language server for a specific file type.

### Repro

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    { "folke/trouble.nvim", opts = {} },
    -- add any other plugins here
  },
})
```

**Comment by folke** [comment]
That's not a bug...

**Comment by maxrzaw** [comment]
I realize this isn't a bug, but is there a way to improve the experience without disabling one of the servers?
These references look identical to me except for the provider. Is there a way to combine duplicate references from different providers?
![image](https://github.com/user-attachments/assets/7d65b23c-291b-436a-ad5d-c1c9dba370de)
