### ISSUE TITLE
bug: Unhandled promise rejection

### ISSUE THREAD

**Issue by idelice** [folke/trouble.nvim#604]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

0.10.1

### Operating system/version

macos 14.3

### Describe the bug

Getting this error when toggling document symbols:

```
Trouble Unhandled promise rejection:
```lua
...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:489: bad argument #2 to 'get_line_col' (number expected, got string)

stack traceback:
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:34: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:48: in function 'reject'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:81: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:78: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:164: in function <...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:160>
	[C]: in function 'pcall'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:73: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:142: in function 'handler'
	.../neovim/0.10.1/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>```
```

### Steps To Reproduce

1. open a java fala
2. toggle document symbols

### Expected Behavior

no error

**Comment by JazzXP** [comment]
I'm getting the same but with Typescript

**Comment by bryangrimes** [comment]
yeah I seem to be getting this all the sudden only with lua files.

**Comment by mattups** [comment]
Python for me, popping up even if Trouble is not triggered

**Comment by jar3k** [comment]
A quick fix: switch trouble.nvim to this commit: https://github.com/folke/trouble.nvim/commit/3dc00c0447c016cd43e03054c3d49436a1f2076d

It seems like this commit https://github.com/folke/trouble.nvim/commit/86746d2b5890139a0270c6693ece219912fd73c0 added an hour ago is causing this issue.
