### ISSUE TITLE
bug: unhandled promise rejection pretty often when LSP is in use

### ISSUE THREAD

**Issue by Silzinc** [folke/trouble.nvim#605]
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have updated the plugin to the latest version before submitting this issue
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.10.1

### Operating system/version

Pop!_OS 22.04

### Describe the bug

Hello! I do not know if it is the right place to ask this, but I am recently facing this error on every cursor move in, for example, a python file with an LSP attached (basedpyright in my example, I had the same issue on lua with lua_ls, c++ with clangd and latex with texlab for example), when I write some assignment

```lua
...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:489: bad argument #2 to 'get_line_col' (number expected, got string)

stack traceback:
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:34: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:48: in function 'reject'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:81: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:78: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:164: in function <...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:160>
	[C]: in function 'pcall'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:73: in function 'cb'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:31: in function 'transition'
	...cal/share/nvim/lazy/trouble.nvim/lua/trouble/promise.lua:45: in function 'resolve'
	...share/nvim/lazy/trouble.nvim/lua/trouble/sources/lsp.lua:142: in function 'handler'
	/usr/local/share/nvim/runtime/lua/vim/lsp/client.lua:687: in function ''
	vim/_editor.lua: in function <vim/_editor.lua:0>
```

Thank you in advance for helping out!

### Steps To Reproduce

1. Configure an LSP for python (or another language).
2. Open some empty python file.
3. Add the line `a = 1`
4. Go to normal mode and try some motions.

### Expected Behavior

No error.

### Repro

```lua
I am sorry, I was not able to write a minimal config for this and to configure an LSP from scratch.
```

**Comment by folke** [comment]
already fixed
