### ISSUE TITLE
how to configure error symbol like this?

### ISSUE THREAD

**Issue by asmin-dev** [folke/trouble.nvim#61]
![Screenshot_2021-07-16-16-03-09-98](https://user-images.githubusercontent.com/67496476/125913896-85c15518-4290-44bc-864d-b8f36c4341b8.jpg)

**Comment by folke** [comment]
You mean the curly underlines? You need a compatible terminal for that. `kitty` is the recommended one

**Comment by asmin-dev** [comment]
Ahh thanks
