### ISSUE TITLE
Jump to next warning or next error

### ISSUE THREAD

**Issue by onsails** [folke/trouble.nvim#63]
There are `next` and `previous` functions, it would be great to have an option to jump a trouble with a specific type. It allows to focus on more severe troubles without distracting to non-significant troubles at the moment.

**Comment by snezhniylis** [comment]
@zalegrala You can take a look at #115. I documented how to use `next` and `previous` functions in there. This also applies to the current implementation, except `opts` passed to these functions.

**Comment by edte** [comment]
could someone please give an example of binding a shortcut key?

**Comment by zalegrala** [comment]
I use `:lua vim.diagnostic.goto_next()<cr>`.  I have zero idea if this is related to this plugin or not.

**Comment by edte** [comment]
thx,it's work fine

```
vim.api.nvim_set_keymap("n", "<a-2>", "<esc><cmd>lua vim.diagnostic.goto_prev()<cr>", {}) -- pre error
vim.api.nvim_set_keymap("n", "<a-3>", "<esc><cmd>lua vim.diagnostic.goto_next()<cr>", {}) -- next error
```

**Comment by liketoeatcheese** [comment]
Hi all. Does anybody know how would I jump to the next error within the workspace without the need to open trouble first? Or jump to the next, and then the trouble window pops up?

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
