### ISSUE TITLE
Errors from BufEnter/BufWinEnter Autocommands on opening after installing trouble 

### ISSUE THREAD

**Issue by nkhlmn** [folke/trouble.nvim#64]
I'm getting the following errors after installing this plugin. I'm still in the process of learning lua and all the new stuff in 0.5 so apologies if this is user error. I have plenty of other stuff going on in my config but i'm not doing anything explicitly with these autocommands.

Thanks for all the work you've put into this!

```
Error detected while processing BufWinEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
Error detected while processing BufEnter Autocommands for "*":
E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
```

```
Error executing vim.schedule lua callback: ...ovim/0.5.0/share/nvim/runtime/lua/vim/lsp/diagnostic.lua:1091: Vim(lua):E5108: Error executing lua [string ":lua"]:1: attempt to index a boolean value
```

**Comment by folke** [comment]
I don't see this error. Could you open that runtime file and post what's on that line (and surrounding lines)?

What commit is that Neovim built?

**Comment by nkhlmn** [comment]
Code is below. This is 0.5.0 stable installed using homebrew on mac.


```
1075
1076   if resolve_optional_value(config.update_in_insert) then
1077     M._clear_scheduled_display(bufnr, client_id)
1078   else
1079     local mode = vim.api.nvim_get_mode()
1080
1081     if string.sub(mode.mode, 1, 1) == 'i' then
1082       M._schedule_display(bufnr, client_id, config)
1083       return
1084     end
1085   end
1086
1087   M.clear(bufnr, client_id)
1088
1089   diagnostics = diagnostics or M.get(bufnr, client_id)
1090
1091   vim.api.nvim_command("doautocmd <nomodeline> User LspDiagnosticsChanged")
1092
1093   if not diagnostics or vim.tbl_isempty(diagnostics) then
1094     return
1095   end
1096
1097   local underline_opts = resolve_optional_value(config.underline)
1098   if underline_opts then
1099     M.set_underline(diagnostics, bufnr, client_id, nil, underline_opts)
1100   end
```

**Comment by nkhlmn** [comment]
Looks like this was only happening when I have my config for this plugin in a `lua/trouble.lua` file. Renaming this file to something else fixes it. I do this with other plugins without any problems (e.g. I can have a `lua/telescope.lua` file). Not sure if you consider this a bug or not.

**Comment by folke** [comment]
Yeah, you should definitely **not** do that. Most people use a Lua config folder for that. `/Lua/config/...`

Plugins will definitely break the way you do it right now, since you're overwriting their global namespace.
