### ISSUE TITLE
Limit message length

### ISSUE THREAD

**Issue by jorrete** [folke/trouble.nvim#69]
Hi,
I am having a veryn long messages coming from tsserver diagnostics. Some times the messages includes the file path and some commands resulting in a messages that do not fit in one line.
Is there any way to shorten the messages.
Thanks.

**Comment by folke** [comment]
Can you show an example? Normally it should all be shown on one line and you can do the hover action to see the multiline message

**Comment by jorrete** [comment]
Here:
![Screenshot from 2021-07-28 22-10-08](https://user-images.githubusercontent.com/1777042/127389285-cc6a60b2-e059-4a0e-9000-d4c45898510d.png)

**Comment by folke** [comment]
This was because you have wrapping enabled in your config. I just pushed a change to always set `nowrap` on the trouble window.
