### ISSUE TITLE
Per window instance of Trouble

### ISSUE THREAD

**Issue by jupblb** [folke/trouble.nvim#74]
Hi. Thanks for your work on this great plugin. Is it possible to have a per window instance of Trouble? This would be highly helpful when using it instead of location lists.

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
