### ISSUE TITLE
Show total number of hits

### ISSUE THREAD

**Issue by johans** [folke/trouble.nvim#76]
Is it possible to get the total number of hits in trouble? I would like to show it in lualine when I send results from telescope. Would also be nice to display what item you are currently displaying out of the total

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
