### ISSUE TITLE
Don't include declaration in lsp_references, etc

### ISSUE THREAD

**Issue by elkowar** [folke/trouble.nvim#78]
In most cases, `includeDeclaration` for requests such as `lsp_references` is most likely not desired.
If one wanted to look at the declaration, one would probably use go to definition. This is especially frustrating when running references _on_ the declaration, as then the item is the one directly under my cursor.

If there is any good reason to keep includeDeclaration set, I'd be nice to have this be configurable somehow!

**Comment by ShiChenCong** [comment]
same situation here 😄

**Comment by ShiChenCong** [comment]
Now fixed, This PR add the `include_declaration` #312

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
