### ISSUE TITLE
Small popup not close after call TroubleToggle

### ISSUE THREAD

**Issue by darteil** [folke/trouble.nvim#80]
Reproducing the problem:

https://user-images.githubusercontent.com/31193144/129874526-8d18c1e7-3545-4587-92bc-03e808eedc58.mp4

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
