### ISSUE TITLE
Improve documentation around BUILTINS

### ISSUE THREAD

**Issue by euoia** [folke/trouble.nvim#81]
I tried the most minimal example and then attempted to format a .lua file.

Here's my Packer config:
```
	-- null-ls bridges the gap between command-line tools and language server.
	-- Adds support for, for example, eslint, prettier, etc.
	use({
		"jose-elias-alvarez/null-ls.nvim",
		requires = { { "neovim/nvim-lspconfig" }, { "nvim-lua/plenary.nvim" } },
		config = function()
			require("null-ls").config({
				sources = { require("null-ls").builtins.formatting.stylua },
			})
			require("lspconfig")["null-ls"].setup({})
		end,
	})
```

But when I ran `:lua vim.lsp.buf.formatting()` was presented with the error:

```
null-ls: failed to run generator: ...e/pack/packer/start/null-ls.nvim/lua/null-ls/helpers.lua:115: command: expected string (executable), got stylua
```

After installing `stylua` the error went away and I was able to format lua files.

Here are some suggestions:
* Consider stating closer to the top of the main README that builtins must installed on the system. Even better, state how they are resolved (does it resolve using the PATH environment variable?).
* Modify the BUILTINS.md document to state that the executables must be installed on the system.
* Consider changing the name BUILTINS to something else, maybe `OUT-OF-THE-BOX` or `SUPPORTED-TOOLS` or sonething.
* Consider changing the error message, and perhaps differentiating between `type(v) == "string"` and `vim.fn.executable(command) > 0`? For example, it might be helpful to state `command` was either not a string, or `command` was not executable (and to refer to the documentation).
* Consider that (in my opinion anyway) the majority of users will be looking to simply use one of the builtins, as opposed to writing their own sources. It might be worth clarifying the distinction better in the main README.

Just for my own curiosity, if the builtins rely on locally provided executables, how does the source specify which version of the tool it is compatible with? Or is that down to the source? For example, what happens if my local version of an executable is missing a feature that is relied up by the source? I think it would be helpful to have this information in either README.md or BUILTINS.md.

Thanks for this plugin, by the way. I really like the approach.

**Comment by gegoune** [comment]
Wrong project? :)

**Comment by euoia** [comment]
Oops! I'm so sorry. This was supposed to be for null-ls. Feel free to delete this issue!
