### ISSUE TITLE
Problem with make and quickfix list.

### ISSUE THREAD

**Issue by vinicius507** [folke/trouble.nvim#87]
Greetings,

Running `:make` and then `:Trouble quickfix` ends up opening more than on Trouble.nvim buffer(in which the cursor starts moving by itself, following the lines of the qflist) and, after closing, gives error:

![image](https://user-images.githubusercontent.com/6608056/131682214-d8ca195f-631c-42ac-bef2-1466098043d3.png)

![image](https://user-images.githubusercontent.com/6608056/131682251-dc554b09-dee1-46d6-92eb-1dfd25f44d8e.png)

**Comment by OnionHat** [comment]
I'm facing the exact same problem as @rajprakharpatel mentioned above, but i'm using `:make` with `:compiler pyunit` option set.

**Comment by YodaEmbedding** [comment]
Same problem with `VimTeX` when disabling chapters via `\includeonly{ }`.

My guess is that this happens whenever there's no exact line number or position associated with a given error.

**Comment by YodaEmbedding** [comment]
See also:

- https://github.com/folke/trouble.nvim/issues/336
