### ISSUE TITLE
Executing jump_close action on the line of file item causes "Invalid buffer id" error.

### ISSUE THREAD

**Issue by spindensity** [folke/trouble.nvim#88]
E.g.:

Look at the picture below, put the cursor on the line "lua\plugins\packer_settings.lua" and execute the jump_close action, An error "invalid buffer id" would be raised.

![Snipaste_2021-09-02_22-45-22](https://user-images.githubusercontent.com/33576822/131865314-3d5b7b47-92b4-4459-9ca5-39ca6c3f86ed.png)
![Snipaste_2021-09-02_22-52-05](https://user-images.githubusercontent.com/33576822/131866223-392e5cfb-e821-448b-b498-eb4e0bbe048b.png)

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
