### ISSUE TITLE
`icons = false` doesn't work?

### ISSUE THREAD

**Issue by vext01** [folke/trouble.nvim#96]
Hi,

Found your plugin today and ran into the following.

First my config snippet:
```
  use {
    "folke/trouble.nvim",
    config = function()
      require("trouble").setup {
          fold_open = "v",
          fold_closed = ">",
          indent_lines = false,
          signs = {
              error = "error",    
              warning = "warn",   
              hint = "hint",
              information = "info"
          },
          icons = false,  
          use_lsp_diagnostic_signs = false
      }
    end   
  }
```

Despite `icons = false`,  nvim says:
```
[Trouble] 'nvim-web-devicons' is not installed. Install it, or set icons=false in your configuration to disable this message
```

Is it a bug?

**Comment by folke** [comment]
Yo probably didnt restart, run PackerSync and restart again?

**Comment by Ajetski** [comment]
I am also having this issue. `[Trouble] 'nvim-web-devicons' is not installed. Install it, or set icons=false in your configuration to disable this message` pops up every time I try to open trouble.nvim despite both having nvim-web-devicons installed and also having `icons = false` set in my config. 

```lua
  use("folke/trouble.nvim", {
    requires = { "nvim-tree/nvim-web-devicons" },
    config = function()
      require 'nvim-web-devicons'.setup {}
      require("trouble").setup {
        icons = false,
        use_lsp_diagnostic_signs = true,
      }
    end
  })
```

**Comment by gregorywaynepower** [comment]
I'm not having the same issues with not being able to disable icons as well, with lazy.nvim

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
