### ISSUE TITLE
Set refresh rate?

### ISSUE THREAD

**Issue by jamesob** [folke/trouble.nvim#97]
By default it seems that trouble is continuously refreshing alerts and errors which can create an annoying editing experience. Is there some way to throttle a refresh of inline warnings to some interval, or (ideally) only upon mode-change or save?

**Comment by b0o** [comment]
> it would be great if there was an option to ignore errors when in insert mode

I think this is the way. @folke would you accept a PR for this?

**Comment by b0o** [comment]
> it would be great if there was an option to ignore errors when in insert mode

I accomplished this in my configuration with the following:

```lua
-- lua/user/trouble.lua

local M = {}

local troubleAutoPrev

function M.disableAutoOpenClose()
  local troubleOpts = require('trouble.config').options
  troubleAutoPrev = {
    open = troubleOpts.auto_open,
    close = troubleOpts.auto_close,
  }
  troubleOpts.auto_open = false
  troubleOpts.auto_close = false
end

function M.restoreAutoOpenClose()
  if troubleAutoPrev == nil then
    return
  end
  local troubleOpts = require('trouble.config').options
  troubleOpts.auto_open = troubleAutoPrev.open
  troubleOpts.auto_close = troubleAutoPrev.close
  troubleAutoPrev = nil
  require('trouble').refresh { auto = troubleOpts.auto_open, provider = 'diagnostics' }
end

vim.cmd [[
  augroup user_trouble
    autocmd!
    autocmd InsertEnter * lua require'user.trouble'.disableAutoOpenClose()
    autocmd InsertLeave * lua require'user.trouble'.restoreAutoOpenClose()
  augroup END
]]

return M
```

**Comment by folke** [comment]
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev
